/**
 * plcSimBridge — fetch wrapper around the /api/plc/sim/* backend routes.
 *
 * All public functions return a normalised object:
 *   { ok: boolean, outputs, trace, last_state, session_id, errors, status }
 *
 * Network errors and non-2xx HTTP responses are caught and surfaced
 * through the `errors` array rather than thrown, so callers can render
 * degraded UI without try/catch boilerplate.
 */

const API_URL = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_URL) || ''

/**
 * Run tick_count scan cycles of a PLC program.
 *
 * @param {object} opts
 * @param {string}  opts.program     — IEC 61131-3 ST source
 * @param {object}  opts.inputs      — map of input variable name → value
 * @param {number}  opts.tick_count  — number of ticks to simulate (default 1)
 * @param {string}  [opts.session_id] — opaque session token (auto-generated by
 *                                      server on first call; pass back to
 *                                      maintain state across calls)
 * @returns {Promise<{ok, session_id, outputs, trace, last_state, errors, status}>}
 */
export async function stepSim({ program, inputs = {}, tick_count = 1, session_id = null } = {}) {
  try {
    const body = { program, inputs, tick_count }
    if (session_id) body.session_id = session_id

    const res = await fetch(`${API_URL}/api/plc/sim/step`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    })

    const status = res.status

    if (!res.ok) {
      let detail = `HTTP ${status}`
      try {
        const errBody = await res.json()
        detail = errBody?.detail ?? detail
      } catch { /* ignore JSON parse failure */ }
      return {
        ok: false,
        status,
        session_id: session_id ?? null,
        outputs: {},
        trace: [],
        last_state: {},
        errors: [detail],
      }
    }

    const data = await res.json()
    return {
      ok: data.ok ?? true,
      status,
      session_id: data.session_id ?? session_id,
      outputs: data.outputs ?? {},
      trace: data.trace ?? [],
      last_state: data.last_state ?? {},
      errors: data.errors ?? [],
    }
  } catch (err) {
    // Network error (DNS failure, CORS, offline, etc.)
    return {
      ok: false,
      status: 0,
      session_id: session_id ?? null,
      outputs: {},
      trace: [],
      last_state: {},
      errors: [err?.message ?? 'Network error'],
    }
  }
}

/**
 * Load a pre-bundled fixture program from the backend.
 *
 * @param {string} name — fixture name, e.g. "blinker" or "conveyor"
 * @returns {Promise<{ok, name, program, inputs, description, errors, status}>}
 */
export async function loadFixture(name) {
  try {
    const res = await fetch(`${API_URL}/api/plc/sim/load_fixture`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ name }),
    })

    const status = res.status

    if (!res.ok) {
      let detail = `HTTP ${status}`
      try {
        const errBody = await res.json()
        detail = errBody?.detail ?? detail
      } catch { /* ignore */ }
      return { ok: false, status, name, program: '', inputs: [], description: '', errors: [detail] }
    }

    const data = await res.json()
    return {
      ok: data.ok ?? true,
      status,
      name: data.name ?? name,
      program: data.program ?? '',
      inputs: data.inputs ?? [],
      description: data.description ?? '',
      errors: [],
    }
  } catch (err) {
    return {
      ok: false,
      status: 0,
      name,
      program: '',
      inputs: [],
      description: '',
      errors: [err?.message ?? 'Network error'],
    }
  }
}
