"""The ``seed`` / promote step — ZERO LLM tokens.

Mirrors Kerf's REAL existing seed mechanism (``seed/publishers/`` — see
``seed/publishers/README.md``).  That contract:

  * one JSON file per part under ``seed/publishers/parts/<slug>.json``,
  * each file is a ``PartDoc`` (``version``/``name``/``distributors`` + the
    optional ``description``/``category``/``manufacturer``/``mpn``/``metadata``
    fields — the exact shape ``create_part`` scaffolds and the library
    ``kind='part'`` row stores),
  * the documented runner (``npm run seed:publishers`` / the not-yet-ported
    ``python -m backend.seed.publishers``) upserts those into the
    ``Common Components`` project of the ``kerf-system`` workspace, idempotent
    by ``(project_id, name)``.

We do NOT invent a new DB schema or a new seed location.  ``seed`` reads
``[x]``-approved families, enumerates them, and emits ready-to-commit
``PartDoc`` JSON (one per passing variant, slug filename) into an output
directory that defaults to ``seed/publishers/parts/`` — the contributor
reviews + commits those files, then runs Kerf's own publishers seeder to
load them.  The STEP solid for each variant is written alongside under
``.parts-out/`` (geometry is never committed); the PartDoc's
``metadata.geometry`` records the family/size + measured bbox/volume so the
solid is reproducible from the committed generator with zero tokens.

The script still never edits a tracked file on its own: it WRITES new
PartDoc files into the chosen ``--out`` dir, prints them, and leaves
``git add`` / commit to the human (the wishlist tick is the review record).
"""

from __future__ import annotations

import json
import os

from kerf_partsgen.enumerate import enumerate_family, parts_out_root
from kerf_partsgen.loader import load_family
from kerf_partsgen.wishlist import parse_wishlist_file, slugify


def default_seed_dir(repo_root: str) -> str:
    # Kerf's documented first-party publisher seed location.
    return os.path.join(repo_root, "seed", "publishers", "parts")


def part_doc_for_variant(family, row: dict, variant) -> dict:
    """Build the canonical PartDoc (matches kerf_api scaffold.run_create_part
    + seed/publishers/parts/*.json shape)."""
    size = str(row.get("size"))
    name = f"{family.name} {size}"
    slug = slugify(f"{family.family_id}-{size}")
    doc = {
        "version": 1,
        "name": name,
        "description": (
            f"{family.name}, size {size}, per {family.standard}. "
            f"Generated by kerf-partsgen from the committed parametric "
            f"generator {family.family_id}.py (MIT)."
        ),
        "category": family.category,
        "manufacturer": "Kerf Workshop",
        "mpn": f"KERF-{family.family_id.upper().replace('-', '')}-{size}",
        "value": size,
        "datasheet_url": "",
        "distributors": [],
        "visibility": "public",
        "metadata": {
            "standard": family.standard,
            "units": "mm",
            "params": row.get("params", {}),
            "geometry": {
                "generator": f"kerf_partsgen/generators/{family.family_id}.py",
                "size": size,
                "kernel_step": f".parts-out/.../{slug}/part.step",
                "measured_bbox_mm": (
                    list(variant.measured_bbox_mm)
                    if variant.measured_bbox_mm
                    else None
                ),
                "measured_volume_mm3": variant.measured_volume_mm3,
            },
        },
    }
    return doc


def seed_wishlist(
    repo_root: str,
    *,
    domain: str = "mechanical",
    out_dir: str | None = None,
    gen_dir: str | None = None,
    wishlist_path: str | None = None,
    out_root: str | None = None,
) -> dict:
    """Enumerate every ``[x]``-approved family and emit PartDoc JSON files.

    Returns a manifest dict {written: [...paths], skipped_fail: int,
    families: int}. Does not modify any tracked file (writes new PartDoc
    files the human then reviews + commits)."""
    wl_path = wishlist_path or os.path.join(
        repo_root, "docs", "parts", "wishlist", f"{domain}.md"
    )
    rows = parse_wishlist_file(wl_path)
    approved = [r for r in rows if r.approved]

    out = out_dir or default_seed_dir(repo_root)
    os.makedirs(out, exist_ok=True)

    written: list[str] = []
    skipped_fail = 0
    for wr in approved:
        family = load_family(wr.family_id, gen_dir)
        fr = enumerate_family(
            wr.family_id, repo_root, gen_dir=gen_dir, domain=domain,
            out_root=out_root,
        )
        by_size = {v.size: v for v in fr.variants}
        for row in family.sizes:
            size = str(row.get("size"))
            v = by_size.get(size)
            if v is None or v.status != "PASS":
                skipped_fail += 1
                continue
            doc = part_doc_for_variant(family, row, v)
            slug = slugify(f"{family.family_id}-{size}")
            dest = os.path.join(out, f"{slug}.json")
            with open(dest, "w", encoding="utf-8") as fh:
                json.dump(doc, fh, indent=2)
            written.append(dest)

    return {
        "families": len(approved),
        "written": written,
        "skipped_fail": skipped_fail,
        "out_dir": out,
        "parts_out": parts_out_root(out_root or repo_root),
    }
