"""Static catalogue of popular embedded boards.

Each entry is a dict with exactly these 12 fields:
  name, slug, vendor, mcu, arch, cpu_freq_mhz, flash_kb, ram_kb,
  voltage_v, has_usb, upload_protocol, source_url

arch values: 'avr' | 'arm-cm0+' | 'arm-cm4f' | 'arm-cm7' | 'xtensa' | 'riscv32imc'
upload_protocol values: 'avrdude' | 'esptool' | 'stm32flash' | 'bossac'
"""

BOARDS: list[dict] = [
    # ── Arduino ──────────────────────────────────────────────────────────────
    {
        "name": "Arduino Uno R3",
        "slug": "arduino-uno-r3",
        "vendor": "Arduino",
        "mcu": "ATmega328P",
        "arch": "avr",
        "cpu_freq_mhz": 16,
        "flash_kb": 32,
        "ram_kb": 2,
        "voltage_v": 5.0,
        "has_usb": False,
        "upload_protocol": "avrdude",
        "source_url": "https://store.arduino.cc/products/arduino-uno-rev3",
    },
    {
        "name": "Arduino Uno R4 Minima",
        "slug": "arduino-uno-r4-minima",
        "vendor": "Arduino",
        "mcu": "RA4M1",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 48,
        "flash_kb": 256,
        "ram_kb": 32,
        "voltage_v": 5.0,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://store.arduino.cc/products/uno-r4-minima",
    },
    {
        "name": "Arduino Uno R4 WiFi",
        "slug": "arduino-uno-r4-wifi",
        "vendor": "Arduino",
        "mcu": "RA4M1",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 48,
        "flash_kb": 256,
        "ram_kb": 32,
        "voltage_v": 5.0,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://store.arduino.cc/products/uno-r4-wifi",
    },
    {
        "name": "Arduino Nano",
        "slug": "arduino-nano",
        "vendor": "Arduino",
        "mcu": "ATmega328P",
        "arch": "avr",
        "cpu_freq_mhz": 16,
        "flash_kb": 32,
        "ram_kb": 2,
        "voltage_v": 5.0,
        "has_usb": True,
        "upload_protocol": "avrdude",
        "source_url": "https://store.arduino.cc/products/arduino-nano",
    },
    {
        "name": "Arduino Mega 2560",
        "slug": "arduino-mega-2560",
        "vendor": "Arduino",
        "mcu": "ATmega2560",
        "arch": "avr",
        "cpu_freq_mhz": 16,
        "flash_kb": 256,
        "ram_kb": 8,
        "voltage_v": 5.0,
        "has_usb": False,
        "upload_protocol": "avrdude",
        "source_url": "https://store.arduino.cc/products/arduino-mega-2560-rev3",
    },
    {
        "name": "Arduino Leonardo",
        "slug": "arduino-leonardo",
        "vendor": "Arduino",
        "mcu": "ATmega32U4",
        "arch": "avr",
        "cpu_freq_mhz": 16,
        "flash_kb": 32,
        "ram_kb": 2,
        "voltage_v": 5.0,
        "has_usb": True,
        "upload_protocol": "avrdude",
        "source_url": "https://store.arduino.cc/products/arduino-leonardo",
    },
    {
        "name": "Arduino Micro",
        "slug": "arduino-micro",
        "vendor": "Arduino",
        "mcu": "ATmega32U4",
        "arch": "avr",
        "cpu_freq_mhz": 16,
        "flash_kb": 32,
        "ram_kb": 2,
        "voltage_v": 5.0,
        "has_usb": True,
        "upload_protocol": "avrdude",
        "source_url": "https://store.arduino.cc/products/arduino-micro",
    },
    {
        "name": "Arduino Due",
        "slug": "arduino-due",
        "vendor": "Arduino",
        "mcu": "ATSAM3X8E",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 84,
        "flash_kb": 512,
        "ram_kb": 96,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://store.arduino.cc/products/arduino-due",
    },
    # ── Adafruit ItsyBitsy ────────────────────────────────────────────────────
    {
        "name": "Adafruit ItsyBitsy M0",
        "slug": "adafruit-itsybitsy-m0",
        "vendor": "Adafruit",
        "mcu": "ATSAMD21G18",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 48,
        "flash_kb": 256,
        "ram_kb": 32,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.adafruit.com/product/3727",
    },
    {
        "name": "Adafruit ItsyBitsy M4",
        "slug": "adafruit-itsybitsy-m4",
        "vendor": "Adafruit",
        "mcu": "ATSAMD51G19",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 120,
        "flash_kb": 512,
        "ram_kb": 192,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.adafruit.com/product/3800",
    },
    {
        "name": "Adafruit ItsyBitsy RP2040",
        "slug": "adafruit-itsybitsy-rp2040",
        "vendor": "Adafruit",
        "mcu": "RP2040",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 133,
        "flash_kb": 8192,
        "ram_kb": 264,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.adafruit.com/product/4888",
    },
    # ── Adafruit Feather ──────────────────────────────────────────────────────
    {
        "name": "Adafruit Feather M0",
        "slug": "adafruit-feather-m0",
        "vendor": "Adafruit",
        "mcu": "ATSAMD21G18",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 48,
        "flash_kb": 256,
        "ram_kb": 32,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.adafruit.com/product/2772",
    },
    {
        "name": "Adafruit Feather M4",
        "slug": "adafruit-feather-m4",
        "vendor": "Adafruit",
        "mcu": "ATSAMD51J19",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 120,
        "flash_kb": 512,
        "ram_kb": 192,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.adafruit.com/product/3857",
    },
    {
        "name": "Adafruit Feather RP2040",
        "slug": "adafruit-feather-rp2040",
        "vendor": "Adafruit",
        "mcu": "RP2040",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 133,
        "flash_kb": 8192,
        "ram_kb": 264,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.adafruit.com/product/4884",
    },
    {
        "name": "Adafruit Feather ESP32-S2",
        "slug": "adafruit-feather-esp32-s2",
        "vendor": "Adafruit",
        "mcu": "ESP32-S2",
        "arch": "xtensa",
        "cpu_freq_mhz": 240,
        "flash_kb": 4096,
        "ram_kb": 320,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "esptool",
        "source_url": "https://www.adafruit.com/product/5000",
    },
    # ── ESP32 family ─────────────────────────────────────────────────────────
    {
        "name": "ESP32-WROOM-32",
        "slug": "esp32-wroom-32",
        "vendor": "Espressif",
        "mcu": "ESP32",
        "arch": "xtensa",
        "cpu_freq_mhz": 240,
        "flash_kb": 4096,
        "ram_kb": 520,
        "voltage_v": 3.3,
        "has_usb": False,
        "upload_protocol": "esptool",
        "source_url": "https://www.espressif.com/en/products/modules/esp32",
    },
    {
        "name": "ESP32-S3",
        "slug": "esp32-s3",
        "vendor": "Espressif",
        "mcu": "ESP32-S3",
        "arch": "xtensa",
        "cpu_freq_mhz": 240,
        "flash_kb": 8192,
        "ram_kb": 512,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "esptool",
        "source_url": "https://www.espressif.com/en/products/socs/esp32-s3",
    },
    {
        "name": "ESP32-C3",
        "slug": "esp32-c3",
        "vendor": "Espressif",
        "mcu": "ESP32-C3",
        "arch": "riscv32imc",
        "cpu_freq_mhz": 160,
        "flash_kb": 4096,
        "ram_kb": 400,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "esptool",
        "source_url": "https://www.espressif.com/en/products/socs/esp32-c3",
    },
    # ── ESP8266 ───────────────────────────────────────────────────────────────
    {
        "name": "ESP8266 NodeMCU",
        "slug": "esp8266-nodemcu",
        "vendor": "Espressif",
        "mcu": "ESP8266",
        "arch": "xtensa",
        "cpu_freq_mhz": 80,
        "flash_kb": 4096,
        "ram_kb": 80,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "esptool",
        "source_url": "https://www.espressif.com/en/products/socs/esp8266",
    },
    # ── Raspberry Pi Pico ─────────────────────────────────────────────────────
    {
        "name": "Raspberry Pi Pico",
        "slug": "raspberry-pi-pico",
        "vendor": "Raspberry Pi",
        "mcu": "RP2040",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 133,
        "flash_kb": 2048,
        "ram_kb": 264,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.raspberrypi.com/products/raspberry-pi-pico/",
    },
    {
        "name": "Raspberry Pi Pico 2",
        "slug": "raspberry-pi-pico-2",
        "vendor": "Raspberry Pi",
        "mcu": "RP2350",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 150,
        "flash_kb": 4096,
        "ram_kb": 520,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.raspberrypi.com/products/raspberry-pi-pico-2/",
    },
    {
        "name": "Raspberry Pi Pico W",
        "slug": "raspberry-pi-pico-w",
        "vendor": "Raspberry Pi",
        "mcu": "RP2040",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 133,
        "flash_kb": 2048,
        "ram_kb": 264,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.raspberrypi.com/products/raspberry-pi-pico/",
    },
    # ── STM32 BlackPill ───────────────────────────────────────────────────────
    {
        "name": "STM32 BlackPill F411",
        "slug": "stm32-blackpill-f411",
        "vendor": "WeAct",
        "mcu": "STM32F411CEU6",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 100,
        "flash_kb": 512,
        "ram_kb": 128,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "stm32flash",
        "source_url": "https://github.com/WeActStudio/WeActStudio.MiniSTM32F4x1",
    },
    {
        "name": "STM32 BlackPill F401",
        "slug": "stm32-blackpill-f401",
        "vendor": "WeAct",
        "mcu": "STM32F401CCU6",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 84,
        "flash_kb": 256,
        "ram_kb": 64,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "stm32flash",
        "source_url": "https://github.com/WeActStudio/WeActStudio.MiniSTM32F4x1",
    },
    # ── STM32 Nucleo ──────────────────────────────────────────────────────────
    {
        "name": "Nucleo F303RE",
        "slug": "nucleo-f303re",
        "vendor": "STMicroelectronics",
        "mcu": "STM32F303RET6",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 72,
        "flash_kb": 512,
        "ram_kb": 64,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "stm32flash",
        "source_url": "https://www.st.com/en/evaluation-tools/nucleo-f303re.html",
    },
    {
        "name": "Nucleo F411RE",
        "slug": "nucleo-f411re",
        "vendor": "STMicroelectronics",
        "mcu": "STM32F411RET6",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 100,
        "flash_kb": 512,
        "ram_kb": 128,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "stm32flash",
        "source_url": "https://www.st.com/en/evaluation-tools/nucleo-f411re.html",
    },
    {
        "name": "Nucleo H743ZI",
        "slug": "nucleo-h743zi",
        "vendor": "STMicroelectronics",
        "mcu": "STM32H743ZIT6",
        "arch": "arm-cm7",
        "cpu_freq_mhz": 480,
        "flash_kb": 2048,
        "ram_kb": 1024,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "stm32flash",
        "source_url": "https://www.st.com/en/evaluation-tools/nucleo-h743zi.html",
    },
    # ── Teensy ────────────────────────────────────────────────────────────────
    {
        "name": "Teensy 4.0",
        "slug": "teensy-4-0",
        "vendor": "PJRC",
        "mcu": "IMXRT1062",
        "arch": "arm-cm7",
        "cpu_freq_mhz": 600,
        "flash_kb": 2048,
        "ram_kb": 1024,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.pjrc.com/store/teensy40.html",
    },
    {
        "name": "Teensy 4.1",
        "slug": "teensy-4-1",
        "vendor": "PJRC",
        "mcu": "IMXRT1062",
        "arch": "arm-cm7",
        "cpu_freq_mhz": 600,
        "flash_kb": 8192,
        "ram_kb": 1024,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.pjrc.com/store/teensy41.html",
    },
    # ── Seeed XIAO ───────────────────────────────────────────────────────────
    {
        "name": "Seeed XIAO RP2040",
        "slug": "seeed-xiao-rp2040",
        "vendor": "Seeed Studio",
        "mcu": "RP2040",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 133,
        "flash_kb": 2048,
        "ram_kb": 264,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.seeedstudio.com/XIAO-RP2040-v1-0-p-5026.html",
    },
    {
        "name": "Seeed XIAO ESP32-C3",
        "slug": "seeed-xiao-esp32-c3",
        "vendor": "Seeed Studio",
        "mcu": "ESP32-C3",
        "arch": "riscv32imc",
        "cpu_freq_mhz": 160,
        "flash_kb": 4096,
        "ram_kb": 400,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "esptool",
        "source_url": "https://www.seeedstudio.com/Seeed-XIAO-ESP32C3-p-5431.html",
    },
    {
        "name": "Seeed XIAO SAMD21",
        "slug": "seeed-xiao-samd21",
        "vendor": "Seeed Studio",
        "mcu": "ATSAMD21G18",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 48,
        "flash_kb": 256,
        "ram_kb": 32,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.seeedstudio.com/Seeeduino-XIAO-Arduino-Microcontroller-SAMD21-Cortex-M0+-p-4426.html",
    },
    # ── Particle ──────────────────────────────────────────────────────────────
    {
        "name": "Particle Photon 2",
        "slug": "particle-photon-2",
        "vendor": "Particle",
        "mcu": "RTL8721DM",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 200,
        "flash_kb": 4096,
        "ram_kb": 3072,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.particle.io/devices/",
    },
    # ── Nordic nRF ───────────────────────────────────────────────────────────
    {
        "name": "nRF52840 Dongle",
        "slug": "nrf52840-dongle",
        "vendor": "Nordic Semiconductor",
        "mcu": "nRF52840",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 64,
        "flash_kb": 1024,
        "ram_kb": 256,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.nordicsemi.com/Products/Development-hardware/nRF52840-Dongle",
    },
    # ── BBC micro:bit ─────────────────────────────────────────────────────────
    {
        "name": "BBC micro:bit V2",
        "slug": "bbc-microbit-v2",
        "vendor": "Micro:bit Educational Foundation",
        "mcu": "nRF52833",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 64,
        "flash_kb": 512,
        "ram_kb": 128,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://microbit.org/buy/",
    },
    # ── Extra boards to ensure 50+ total ────────────────────────────────────
    {
        "name": "Arduino Nano 33 IoT",
        "slug": "arduino-nano-33-iot",
        "vendor": "Arduino",
        "mcu": "ATSAMD21G18",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 48,
        "flash_kb": 256,
        "ram_kb": 32,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://store.arduino.cc/products/arduino-nano-33-iot",
    },
    {
        "name": "Arduino Nano 33 BLE",
        "slug": "arduino-nano-33-ble",
        "vendor": "Arduino",
        "mcu": "nRF52840",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 64,
        "flash_kb": 1024,
        "ram_kb": 256,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://store.arduino.cc/products/arduino-nano-33-ble",
    },
    {
        "name": "Arduino Nano Every",
        "slug": "arduino-nano-every",
        "vendor": "Arduino",
        "mcu": "ATMega4809",
        "arch": "avr",
        "cpu_freq_mhz": 20,
        "flash_kb": 48,
        "ram_kb": 6,
        "voltage_v": 5.0,
        "has_usb": True,
        "upload_protocol": "avrdude",
        "source_url": "https://store.arduino.cc/products/arduino-nano-every",
    },
    {
        "name": "Arduino MKR WiFi 1010",
        "slug": "arduino-mkr-wifi-1010",
        "vendor": "Arduino",
        "mcu": "ATSAMD21G18",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 48,
        "flash_kb": 256,
        "ram_kb": 32,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://store.arduino.cc/products/arduino-mkr-wifi-1010",
    },
    {
        "name": "Arduino Portenta H7",
        "slug": "arduino-portenta-h7",
        "vendor": "Arduino",
        "mcu": "STM32H747XI",
        "arch": "arm-cm7",
        "cpu_freq_mhz": 480,
        "flash_kb": 2048,
        "ram_kb": 1024,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "stm32flash",
        "source_url": "https://store.arduino.cc/products/portenta-h7",
    },
    {
        "name": "ESP32-S2",
        "slug": "esp32-s2",
        "vendor": "Espressif",
        "mcu": "ESP32-S2",
        "arch": "xtensa",
        "cpu_freq_mhz": 240,
        "flash_kb": 4096,
        "ram_kb": 320,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "esptool",
        "source_url": "https://www.espressif.com/en/products/socs/esp32-s2",
    },
    {
        "name": "ESP32-H2",
        "slug": "esp32-h2",
        "vendor": "Espressif",
        "mcu": "ESP32-H2",
        "arch": "riscv32imc",
        "cpu_freq_mhz": 96,
        "flash_kb": 4096,
        "ram_kb": 320,
        "voltage_v": 3.3,
        "has_usb": False,
        "upload_protocol": "esptool",
        "source_url": "https://www.espressif.com/en/products/socs/esp32-h2",
    },
    {
        "name": "Seeed XIAO ESP32-S3",
        "slug": "seeed-xiao-esp32-s3",
        "vendor": "Seeed Studio",
        "mcu": "ESP32-S3",
        "arch": "xtensa",
        "cpu_freq_mhz": 240,
        "flash_kb": 8192,
        "ram_kb": 512,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "esptool",
        "source_url": "https://www.seeedstudio.com/XIAO-ESP32S3-p-5627.html",
    },
    {
        "name": "Seeed XIAO nRF52840",
        "slug": "seeed-xiao-nrf52840",
        "vendor": "Seeed Studio",
        "mcu": "nRF52840",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 64,
        "flash_kb": 1024,
        "ram_kb": 256,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.seeedstudio.com/Seeed-XIAO-BLE-nRF52840-p-5201.html",
    },
    {
        "name": "Nucleo L476RG",
        "slug": "nucleo-l476rg",
        "vendor": "STMicroelectronics",
        "mcu": "STM32L476RGT6",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 80,
        "flash_kb": 1024,
        "ram_kb": 128,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "stm32flash",
        "source_url": "https://www.st.com/en/evaluation-tools/nucleo-l476rg.html",
    },
    {
        "name": "Nucleo G031K8",
        "slug": "nucleo-g031k8",
        "vendor": "STMicroelectronics",
        "mcu": "STM32G031K8T6",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 64,
        "flash_kb": 64,
        "ram_kb": 8,
        "voltage_v": 3.3,
        "has_usb": False,
        "upload_protocol": "stm32flash",
        "source_url": "https://www.st.com/en/evaluation-tools/nucleo-g031k8.html",
    },
    {
        "name": "Adafruit Circuit Playground Bluefruit",
        "slug": "adafruit-circuit-playground-bluefruit",
        "vendor": "Adafruit",
        "mcu": "nRF52840",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 64,
        "flash_kb": 1024,
        "ram_kb": 256,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.adafruit.com/product/4333",
    },
    {
        "name": "Adafruit Metro M4 Express",
        "slug": "adafruit-metro-m4-express",
        "vendor": "Adafruit",
        "mcu": "ATSAMD51J19",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 120,
        "flash_kb": 512,
        "ram_kb": 192,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.adafruit.com/product/3382",
    },
    {
        "name": "Adafruit Grand Central M4",
        "slug": "adafruit-grand-central-m4",
        "vendor": "Adafruit",
        "mcu": "ATSAMD51P20",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 120,
        "flash_kb": 1024,
        "ram_kb": 256,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.adafruit.com/product/4064",
    },
    {
        "name": "Teensy 3.2",
        "slug": "teensy-3-2",
        "vendor": "PJRC",
        "mcu": "MK20DX256",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 72,
        "flash_kb": 256,
        "ram_kb": 64,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.pjrc.com/store/teensy32.html",
    },
    {
        "name": "Sparkfun Pro Micro",
        "slug": "sparkfun-pro-micro",
        "vendor": "SparkFun",
        "mcu": "ATmega32U4",
        "arch": "avr",
        "cpu_freq_mhz": 16,
        "flash_kb": 32,
        "ram_kb": 2,
        "voltage_v": 5.0,
        "has_usb": True,
        "upload_protocol": "avrdude",
        "source_url": "https://www.sparkfun.com/products/12640",
    },
    {
        "name": "Sparkfun Thing Plus RP2040",
        "slug": "sparkfun-thing-plus-rp2040",
        "vendor": "SparkFun",
        "mcu": "RP2040",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 133,
        "flash_kb": 16384,
        "ram_kb": 264,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.sparkfun.com/products/17745",
    },
    {
        "name": "Wemos D1 Mini",
        "slug": "wemos-d1-mini",
        "vendor": "Wemos",
        "mcu": "ESP8266",
        "arch": "xtensa",
        "cpu_freq_mhz": 80,
        "flash_kb": 4096,
        "ram_kb": 80,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "esptool",
        "source_url": "https://www.wemos.cc/en/latest/d1/d1_mini.html",
    },
    {
        "name": "Wemos S2 Mini",
        "slug": "wemos-s2-mini",
        "vendor": "Wemos",
        "mcu": "ESP32-S2",
        "arch": "xtensa",
        "cpu_freq_mhz": 240,
        "flash_kb": 4096,
        "ram_kb": 320,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "esptool",
        "source_url": "https://www.wemos.cc/en/latest/s2/s2_mini.html",
    },
    {
        "name": "RP2040-Zero",
        "slug": "rp2040-zero",
        "vendor": "Waveshare",
        "mcu": "RP2040",
        "arch": "arm-cm0+",
        "cpu_freq_mhz": 133,
        "flash_kb": 2048,
        "ram_kb": 264,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "bossac",
        "source_url": "https://www.waveshare.com/rp2040-zero.htm",
    },
    {
        "name": "Nucleo WB55RG",
        "slug": "nucleo-wb55rg",
        "vendor": "STMicroelectronics",
        "mcu": "STM32WB55RGV6",
        "arch": "arm-cm4f",
        "cpu_freq_mhz": 64,
        "flash_kb": 1024,
        "ram_kb": 256,
        "voltage_v": 3.3,
        "has_usb": True,
        "upload_protocol": "stm32flash",
        "source_url": "https://www.st.com/en/evaluation-tools/p-nucleo-wb55.html",
    },
]
