# kerf-electronics RF & fiber-optic link budget sub-package.
# Public API is re-exported from link.py.
from kerf_electronics.linkbudget.link import (
    # RF
    fspl_db,
    eirp_dbw,
    received_power_dbw,
    antenna_gain_from_aperture,
    antenna_aperture_from_gain,
    g_over_t,
    noise_figure_cascade,
    system_noise_temp,
    thermal_noise_floor_dbw,
    cn_ratio_db,
    eb_n0_db,
    required_eb_n0_bpsk,
    required_eb_n0_qpsk,
    required_eb_n0_qam,
    required_eb_n0_psk,
    ber_bpsk,
    ber_qpsk,
    ber_qam,
    ber_psk,
    shannon_capacity,
    spectral_efficiency,
    rain_attenuation_db,
    atmospheric_attenuation_db,
    rf_link_budget,
    # Fiber
    fiber_power_budget,
    chromatic_dispersion_bandwidth,
    modal_dispersion_bandwidth,
    fiber_osnr,
)

__all__ = [
    "fspl_db",
    "eirp_dbw",
    "received_power_dbw",
    "antenna_gain_from_aperture",
    "antenna_aperture_from_gain",
    "g_over_t",
    "noise_figure_cascade",
    "system_noise_temp",
    "thermal_noise_floor_dbw",
    "cn_ratio_db",
    "eb_n0_db",
    "required_eb_n0_bpsk",
    "required_eb_n0_qpsk",
    "required_eb_n0_qam",
    "required_eb_n0_psk",
    "ber_bpsk",
    "ber_qpsk",
    "ber_qam",
    "ber_psk",
    "shannon_capacity",
    "spectral_efficiency",
    "rain_attenuation_db",
    "atmospheric_attenuation_db",
    "rf_link_budget",
    "fiber_power_budget",
    "chromatic_dispersion_bandwidth",
    "modal_dispersion_bandwidth",
    "fiber_osnr",
]
