"""
Fanuc 3-axis post-processor (T7 tool-DB integration).

Dialect notes
-------------
- N-numbers:  optional per-line sequence numbers, incremented by 10.
              Disabled when ``opts.no_n_numbers`` is True.
- ``G90``     absolute positioning.
- ``G94``     feed-per-minute.
- ``G17``     XY-plane.
- ``G21``     metric (mm).
- ``G54``     work-coordinate system (WCS 1).
- ``M6 T<n>`` tool call; uses ``tool.id`` when a Tool is attached.
- ``S<rpm> M3`` spindle on CW.
- ``M8``      flood coolant on.
- ``M7``      mist coolant on.
- ``G43 H<n>`` tool-length compensation.
- ``G1 Z…``   plunge move.
- ``M9 M5``   coolant off, spindle off.
- ``M30``     program end + rewind.
- Comments:   ``(...)`` parenthetical (RS-274D / Fanuc style).

Feed precedence
---------------
PostOpts3 caller-supplied values > Tool.feed_rate_mm_min / Tool.plunge_rate_mm_min.
"""

from __future__ import annotations

from kerf_cam.posts_common import PostOpts3, tool_comment_line


def emit(cl_points: list[dict], opts: PostOpts3) -> str:
    """Emit a complete Fanuc 3-axis G-code program.

    Parameters
    ----------
    cl_points : list of ``{x, y, z}`` dicts — tool-tip positions (mm).
                An optional ``"feed"`` or ``"feed_rate"`` key overrides
                ``opts.feed_cut_mm_min`` for that move.
    opts      : PostOpts3 instance.

    Returns
    -------
    str  — complete G-code program.
    """
    opts.apply_tool_defaults()

    # Fanuc: M6 uses numeric tool_number; tool.id appears only in the comment.
    _n = _make_seq(opts.no_n_numbers)
    lines: list[str] = []

    # --- Header ---
    lines.append(f"{_n()}(GENERATED BY KERF CAM - FANUC 3-AXIS POST)")
    if opts.tool is not None:
        lines.append(f"{_n()}{tool_comment_line(opts.tool, 'paren')}")
    lines.append(f"{_n()}G90 G94 G17 G21")
    lines.append(f"{_n()}G54")
    lines.append(f"{_n()}M6 T{opts.tool_number}")
    lines.append(f"{_n()}G43 H{opts.tool_number}")
    lines.append(f"{_n()}G0 Z50.000")
    lines.append(f"{_n()}S{opts.spindle_rpm} M3")
    if opts.coolant == "flood":
        lines.append(f"{_n()}M8")
    elif opts.coolant == "mist":
        lines.append(f"{_n()}M7")

    if not cl_points:
        lines.append(f"{_n()}G0 Z50.000")
        lines.append(f"{_n()}G49")
        lines.append(f"{_n()}M9")
        lines.append(f"{_n()}M5")
        lines.append(f"{_n()}M30")
        return "\n".join(lines)

    # --- Rapid to first XY ---
    p0 = cl_points[0]
    lines.append(
        f"{_n()}G0 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z'] + 2.0:.3f} "
        f"F{opts.feed_rapid_mm_min:.0f}"
    )
    # --- Plunge to cut Z ---
    lines.append(
        f"{_n()}G1 Z{p0['z']:.3f} F{opts.feed_plunge_mm_min:.0f}"
    )

    # --- Cutting moves ---
    prev_feed: float | None = None
    for pt in cl_points:
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(
            f"{_n()}G1 X{pt['x']:.3f} Y{pt['y']:.3f} Z{pt['z']:.3f}{feed_word}"
        )

    # --- Footer ---
    lines.append(f"{_n()}G0 Z50.000 F{opts.feed_rapid_mm_min:.0f}")
    lines.append(f"{_n()}G49")
    lines.append(f"{_n()}M9")
    lines.append(f"{_n()}M5")
    lines.append(f"{_n()}M30")

    return "\n".join(lines)


def _make_seq(no_n_numbers: bool):
    """Return a callable that yields N-number prefixes or empty strings."""
    counter = [0]

    def _next() -> str:
        if no_n_numbers:
            return ""
        counter[0] += 10
        return f"N{counter[0]} "

    return _next
