"""
GRBL 3-axis post-processor (T7 tool-DB integration).

Dialect notes
-------------
- ``%``              tape-start / tape-end markers.
- ``G90``            absolute positioning.
- ``G94``            feed-per-minute.
- ``G17``            XY-plane.
- ``G21``            metric (mm).
- ``G54``            work offset.
- ``(M6 T<n>)``      **comment only** — GRBL has no automatic tool changer.
                     The operator must manually load the tool and re-zero Z.
                     A comment is emitted so the setup sheet is self-documenting.
- ``S<rpm> M3``      spindle on CW (PWM duty on Grbl ≤ 1.1; S units on GRBL 2).
- Coolant:           GRBL does not have M7/M8 flood/mist by default.
                     We emit a ``(M8 FLOOD)`` / ``(M7 MIST)`` comment so
                     the operator can wire a relay if present.
- ``M5``             spindle off.
- ``M30``            program end + rewind.
- Comments:          ``;`` prefix (GRBL / LinuxCNC style).

GRBL M6 rationale
-----------------
GRBL (all versions through 1.1h and the GRBL-HAL fork) has no built-in tool
changer.  Emitting a bare ``M6`` would either:
  (a) halt the program on controllers with ``M6`` defined as a pause, or
  (b) raise an alarm ("unsupported command") on controllers without it.
Emitting a ``(M6 T<n>)`` comment is the established practice for GRBL output
(used by Carbide Create, CNC.js defaults, and Easel): the comment is visible
in every streaming program but causes no motion or alarm.  The operator sees
which tool number to load before pressing Cycle Start.

Feed precedence
---------------
PostOpts3 caller-supplied values > Tool.feed_rate_mm_min / Tool.plunge_rate_mm_min.
"""

from __future__ import annotations

from kerf_cam.posts_common import PostOpts3, tool_comment_line


def emit(cl_points: list[dict], opts: PostOpts3) -> str:
    """Emit a complete GRBL 3-axis G-code program.

    Parameters
    ----------
    cl_points : list of ``{x, y, z}`` dicts — tool-tip positions (mm).
                An optional ``"feed"`` or ``"feed_rate"`` key overrides
                ``opts.feed_cut_mm_min`` for that move.
    opts      : PostOpts3 instance.

    Returns
    -------
    str  — complete G-code program.
    """
    opts.apply_tool_defaults()

    # GRBL: M6 is a comment only (no tool changer).
    # tool_number is used; tool.id appears only in the tool-comment line.
    lines: list[str] = []

    # --- Tape start ---
    lines.append("%")

    # --- Header ---
    lines.append("; Generated by Kerf CAM — GRBL 3-axis post")
    if opts.tool is not None:
        lines.append(tool_comment_line(opts.tool, "semicolon"))
    lines.append("G90 G94 G17 G21")
    lines.append("G54")
    # GRBL has no tool changer — emit a comment only.
    lines.append(f"(M6 T{opts.tool_number})")
    lines.append(f"G0 Z50.000")
    lines.append(f"S{opts.spindle_rpm} M3")
    if opts.coolant == "flood":
        lines.append("(M8 FLOOD)")
    elif opts.coolant == "mist":
        lines.append("(M7 MIST)")

    if not cl_points:
        lines.extend(["G0 Z50.000", "M5", "M30", "%"])
        return "\n".join(lines)

    # --- Rapid to first XY ---
    p0 = cl_points[0]
    lines.append(
        f"G0 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z'] + 2.0:.3f} "
        f"F{opts.feed_rapid_mm_min:.0f}"
    )
    # --- Plunge to cut Z ---
    lines.append(
        f"G1 Z{p0['z']:.3f} F{opts.feed_plunge_mm_min:.0f}"
    )

    # --- Cutting moves ---
    prev_feed: float | None = None
    for pt in cl_points:
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(
            f"G1 X{pt['x']:.3f} Y{pt['y']:.3f} Z{pt['z']:.3f}{feed_word}"
        )

    # --- Footer ---
    lines.append(f"G0 Z50.000 F{opts.feed_rapid_mm_min:.0f}")
    lines.append("M5")
    lines.append("M30")
    lines.append("%")

    return "\n".join(lines)
