"""
Mach3 3-axis post-processor (T7 tool-DB integration).

Dialect notes
-------------
- No ``%`` tape markers  (Mach3 does not need them).
- ``G90``                absolute positioning.
- ``G94``                feed-per-minute.
- ``G17``                XY-plane.
- ``G21``                metric (mm).
- ``G54``                work-coordinate system.
- ``T<n> M6``            tool call: Mach3 convention is ``T<n>`` on its own
                         line to request the tool, then ``M6`` to execute
                         the change.  ``tool.id`` is used when a Tool is
                         attached.
- ``S<rpm> M3``          spindle on CW.
- ``M8``                 flood coolant on.
- ``M7``                 mist coolant on.
- ``G43 H<n>``           tool-length compensation.
- ``G1 Z…``              plunge move.
- ``M9 M5``              coolant off, spindle off.
- ``M30``                program end + rewind.
- Comments:              ``(...)`` parenthetical (Mach3 / RS-274D style).

Feed precedence
---------------
PostOpts3 caller-supplied values > Tool.feed_rate_mm_min / Tool.plunge_rate_mm_min.
"""

from __future__ import annotations

from kerf_cam.posts_common import PostOpts3, tool_comment_line


def emit(cl_points: list[dict], opts: PostOpts3) -> str:
    """Emit a complete Mach3 3-axis G-code program.

    Parameters
    ----------
    cl_points : list of ``{x, y, z}`` dicts — tool-tip positions (mm).
                An optional ``"feed"`` or ``"feed_rate"`` key overrides
                ``opts.feed_cut_mm_min`` for that move.
    opts      : PostOpts3 instance.

    Returns
    -------
    str  — complete G-code program.
    """
    opts.apply_tool_defaults()

    # Mach3: T<n> M6 tool call; tool.id is only used in the comment.
    lines: list[str] = []

    # --- Header ---
    lines.append("(Generated by Kerf CAM - Mach3 3-axis post)")
    if opts.tool is not None:
        lines.append(tool_comment_line(opts.tool, "paren"))
    lines.append("G90 G94 G17 G21")
    lines.append("G54")
    lines.append(f"T{opts.tool_number} M6")
    lines.append(f"G43 H{opts.tool_number}")
    lines.append(f"G0 Z50.000")
    lines.append(f"S{opts.spindle_rpm} M3")
    if opts.coolant == "flood":
        lines.append("M8")
    elif opts.coolant == "mist":
        lines.append("M7")

    if not cl_points:
        lines.extend(["G0 Z50.000", "G49", "M9", "M5", "M30"])
        return "\n".join(lines)

    # --- Rapid to first XY ---
    p0 = cl_points[0]
    lines.append(
        f"G0 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z'] + 2.0:.3f} "
        f"F{opts.feed_rapid_mm_min:.0f}"
    )
    # --- Plunge to cut Z ---
    lines.append(
        f"G1 Z{p0['z']:.3f} F{opts.feed_plunge_mm_min:.0f}"
    )

    # --- Cutting moves ---
    prev_feed: float | None = None
    for pt in cl_points:
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(
            f"G1 X{pt['x']:.3f} Y{pt['y']:.3f} Z{pt['z']:.3f}{feed_word}"
        )

    # --- Footer ---
    lines.append(f"G0 Z50.000 F{opts.feed_rapid_mm_min:.0f}")
    lines.append("G49")
    lines.append("M9")
    lines.append("M5")
    lines.append("M30")

    return "\n".join(lines)
