"""kerf_firmware.catalogue.actuators — Embedded actuator catalogue (30+ entries).

Each entry is a dict with:
  name              str   — unique part name / model identifier
  category          str   — e.g. "servo", "stepper", "dc_motor", "led", "relay"
  protocol          str   — control interface: "PWM", "GPIO", "I2C", "SPI", "UART", "Analog"
  address           int|None  — I2C address for bus-addressed actuators, None otherwise
  datasheet_url     str   — canonical datasheet / product page URL
  arduino_library   str   — primary Arduino/PlatformIO library name
  supply_voltage    list[float]  — acceptable VCC values in volts
  current_draw_mA   float — typical / rated current in milliamps
  description       str   — one-line plain-English description
"""
from __future__ import annotations

from typing import Any

ACTUATORS: list[dict[str, Any]] = [
    # ── Servo motors ─────────────────────────────────────────────────────────
    {
        "name": "SG90",
        "category": "servo",
        "protocol": "PWM",
        "address": None,
        "datasheet_url": "http://www.ee.ic.ac.uk/pcheung/teaching/DE1_EE/stores/sg90_datasheet.pdf",
        "arduino_library": "Servo",
        "supply_voltage": [4.8, 5.0],
        "current_draw_mA": 500.0,
        "description": "Micro 9 g servo, 0–180° rotation, popular in hobby robotics.",
    },
    {
        "name": "MG996R",
        "category": "servo",
        "protocol": "PWM",
        "address": None,
        "datasheet_url": "https://www.electronicoscaldas.com/datasheet/MG996R_Tower-Pro.pdf",
        "arduino_library": "Servo",
        "supply_voltage": [4.8, 7.2],
        "current_draw_mA": 2500.0,
        "description": "Metal-gear servo, 10 kg·cm torque, suitable for robotic arms.",
    },
    {
        "name": "DS3225",
        "category": "servo",
        "protocol": "PWM",
        "address": None,
        "datasheet_url": "https://www.dsservo.com/en/d_file/DS3225.pdf",
        "arduino_library": "Servo",
        "supply_voltage": [6.0, 8.4],
        "current_draw_mA": 2300.0,
        "description": "25 kg·cm waterproof digital servo for marine/outdoor use.",
    },
    # ── Stepper motors ────────────────────────────────────────────────────────
    {
        "name": "NEMA 17",
        "category": "stepper",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.makerbot.com/industries/education/3d-printing-curriculum/",
        "arduino_library": "AccelStepper",
        "supply_voltage": [12.0, 24.0],
        "current_draw_mA": 1700.0,
        "description": "Standard frame stepper motor used in 3-D printers and CNC machines.",
    },
    {
        "name": "NEMA 23",
        "category": "stepper",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.omc-stepperonline.com/nema-23-stepper-motor",
        "arduino_library": "AccelStepper",
        "supply_voltage": [24.0, 48.0],
        "current_draw_mA": 2800.0,
        "description": "Higher-torque stepper motor for heavier CNC/router applications.",
    },
    {
        "name": "28BYJ-48",
        "category": "stepper",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.mouser.com/datasheet/2/758/steppermotor28byj_48-1143075.pdf",
        "arduino_library": "Stepper",
        "supply_voltage": [5.0],
        "current_draw_mA": 240.0,
        "description": "Low-cost unipolar 5 V stepper with ULN2003 driver board.",
    },
    # ── DC motors ─────────────────────────────────────────────────────────────
    {
        "name": "N20 DC Gearmotor",
        "category": "dc_motor",
        "protocol": "PWM",
        "address": None,
        "datasheet_url": "https://www.pololu.com/product/2365",
        "arduino_library": "",
        "supply_voltage": [3.0, 12.0],
        "current_draw_mA": 100.0,
        "description": "Miniature N20 metal-gearbox DC motor, many gear ratios available.",
    },
    {
        "name": "775 DC Motor",
        "category": "dc_motor",
        "protocol": "PWM",
        "address": None,
        "datasheet_url": "https://www.robotshop.com/products/dc-motor-775",
        "arduino_library": "",
        "supply_voltage": [12.0, 24.0],
        "current_draw_mA": 5000.0,
        "description": "High-power 775-series brushed DC motor for power tools / carts.",
    },
    # ── Motor drivers / controllers ───────────────────────────────────────────
    {
        "name": "L298N",
        "category": "motor_driver",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/l298.pdf",
        "arduino_library": "",
        "supply_voltage": [5.0, 35.0],
        "current_draw_mA": 4000.0,
        "description": "Dual H-bridge motor driver, up to 2 A per channel.",
    },
    {
        "name": "DRV8825",
        "category": "stepper_driver",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/drv8825.pdf",
        "arduino_library": "",
        "supply_voltage": [8.2, 45.0],
        "current_draw_mA": 2500.0,
        "description": "Micro-stepping stepper driver (up to 1/32 step), used in 3-D printers.",
    },
    {
        "name": "TMC2208",
        "category": "stepper_driver",
        "protocol": "UART",
        "address": None,
        "datasheet_url": "https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2208_datasheet_rev1.09.pdf",
        "arduino_library": "TMCStepper",
        "supply_voltage": [4.75, 36.0],
        "current_draw_mA": 2000.0,
        "description": "Silent stepper driver with StealthChop2 and UART configuration.",
    },
    {
        "name": "PCA9685",
        "category": "pwm_controller",
        "protocol": "I2C",
        "address": 0x40,
        "datasheet_url": "https://www.nxp.com/docs/en/data-sheet/PCA9685.pdf",
        "arduino_library": "Adafruit PWM Servo Driver Library",
        "supply_voltage": [2.3, 5.5],
        "current_draw_mA": 10.0,
        "description": "16-channel 12-bit PWM/servo driver over I2C (up to 62 devices).",
    },
    # ── LED / lighting ────────────────────────────────────────────────────────
    {
        "name": "WS2812B",
        "category": "addressable_led",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf",
        "arduino_library": "FastLED",
        "supply_voltage": [4.5, 5.5],
        "current_draw_mA": 60.0,
        "description": "RGB addressable LED with integrated driver, single-wire protocol.",
    },
    {
        "name": "SK6812",
        "category": "addressable_led",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://cdn-shop.adafruit.com/product-files/2757/p2757_SK6812RGBW_REV01.pdf",
        "arduino_library": "FastLED",
        "supply_voltage": [3.5, 5.3],
        "current_draw_mA": 60.0,
        "description": "RGBW addressable LED (adds white channel over WS2812B).",
    },
    {
        "name": "APA102",
        "category": "addressable_led",
        "protocol": "SPI",
        "address": None,
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/APA102.pdf",
        "arduino_library": "FastLED",
        "supply_voltage": [5.0],
        "current_draw_mA": 60.0,
        "description": "SPI-controlled RGB LED with global brightness control per pixel.",
    },
    # ── Relays ────────────────────────────────────────────────────────────────
    {
        "name": "5V Single-Channel Relay",
        "category": "relay",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.songle.com/relay-datasheet/",
        "arduino_library": "",
        "supply_voltage": [5.0],
        "current_draw_mA": 70.0,
        "description": "Optocoupler-isolated single-channel relay module (10 A / 250 VAC).",
    },
    {
        "name": "4-Channel Relay Module",
        "category": "relay",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.electronicoscaldas.com/datasheet/4-Channel-Relay-Module-Datasheet.pdf",
        "arduino_library": "",
        "supply_voltage": [5.0],
        "current_draw_mA": 300.0,
        "description": "Four optically-isolated relay channels on a single breakout board.",
    },
    # ── Solenoids / valves ────────────────────────────────────────────────────
    {
        "name": "Solenoid Valve 12V",
        "category": "solenoid",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.adafruit.com/product/996",
        "arduino_library": "",
        "supply_voltage": [12.0],
        "current_draw_mA": 400.0,
        "description": "Normally-closed 12 V solenoid valve for water/fluid control.",
    },
    {
        "name": "Push-Pull Solenoid 5V",
        "category": "solenoid",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.sparkfun.com/datasheets/Robotics/Solenoid.pdf",
        "arduino_library": "",
        "supply_voltage": [5.0],
        "current_draw_mA": 500.0,
        "description": "Miniature 5 V push/pull solenoid for locks, latches, and actuators.",
    },
    # ── OLED / LCD displays ───────────────────────────────────────────────────
    {
        "name": "SSD1306 OLED 128x64",
        "category": "display",
        "protocol": "I2C",
        "address": 0x3C,
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf",
        "arduino_library": "Adafruit SSD1306",
        "supply_voltage": [3.3, 5.0],
        "current_draw_mA": 20.0,
        "description": "0.96″ 128×64 monochrome OLED display, very common in Arduino projects.",
    },
    {
        "name": "SH1106 OLED 128x64",
        "category": "display",
        "protocol": "I2C",
        "address": 0x3C,
        "datasheet_url": "https://www.displayfuture.com/Display/datasheet/controller/SH1106.pdf",
        "arduino_library": "U8g2",
        "supply_voltage": [3.3, 5.0],
        "current_draw_mA": 20.0,
        "description": "1.3″ 128×64 OLED with SH1106 controller (slightly larger than SSD1306).",
    },
    {
        "name": "ST7735 TFT 128x160",
        "category": "display",
        "protocol": "SPI",
        "address": None,
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/ST7735R_V0.2.pdf",
        "arduino_library": "Adafruit ST7735 and ST7789 Library",
        "supply_voltage": [3.3],
        "current_draw_mA": 50.0,
        "description": "1.8″ 128×160 TFT colour display with SPI interface.",
    },
    {
        "name": "ILI9341 TFT 240x320",
        "category": "display",
        "protocol": "SPI",
        "address": None,
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf",
        "arduino_library": "Adafruit ILI9341",
        "supply_voltage": [3.3],
        "current_draw_mA": 80.0,
        "description": "2.8″ 240×320 TFT colour display — popular for GUI-equipped projects.",
    },
    {
        "name": "LCD 16x2 (HD44780)",
        "category": "display",
        "protocol": "I2C",
        "address": 0x27,
        "datasheet_url": "https://www.sparkfun.com/datasheets/LCD/HD44780.pdf",
        "arduino_library": "LiquidCrystal I2C",
        "supply_voltage": [5.0],
        "current_draw_mA": 1.5,
        "description": "Classic 16-character × 2-row character LCD with PCF8574 I2C backpack.",
    },
    # ── Buzzers / speakers ────────────────────────────────────────────────────
    {
        "name": "Passive Buzzer 5V",
        "category": "buzzer",
        "protocol": "PWM",
        "address": None,
        "datasheet_url": "https://www.murata.com/en-us/products/productdata/8796836757534/PKMSERIES.pdf",
        "arduino_library": "",
        "supply_voltage": [3.3, 5.0],
        "current_draw_mA": 30.0,
        "description": "Passive piezo buzzer, frequency controlled by MCU PWM.",
    },
    {
        "name": "Active Buzzer 5V",
        "category": "buzzer",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://components101.com/misc/buzzer-pinout-working-datasheet",
        "arduino_library": "",
        "supply_voltage": [3.5, 5.5],
        "current_draw_mA": 30.0,
        "description": "Self-oscillating active buzzer — on/off only, fixed frequency.",
    },
    # ── BLDC / ESC ────────────────────────────────────────────────────────────
    {
        "name": "Generic 30A ESC",
        "category": "esc",
        "protocol": "PWM",
        "address": None,
        "datasheet_url": "https://hobbyking.com/en_us/hobbykingtm-ss-series-30-40a-esc-ubec-3a.html",
        "arduino_library": "Servo",
        "supply_voltage": [7.4, 11.1],
        "current_draw_mA": 30000.0,
        "description": "30 A brushless ESC for UAV/RC vehicles, controlled via servo PWM.",
    },
    # ── Heating / Peltier ────────────────────────────────────────────────────
    {
        "name": "TEC1-12706 Peltier",
        "category": "peltier",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://datasheetspdf.com/pdf/807804/WonjoTech/TEC1-12706/1",
        "arduino_library": "",
        "supply_voltage": [12.0],
        "current_draw_mA": 6000.0,
        "description": "Thermoelectric cooling module, 60 W, 12 V, 6 A.",
    },
    # ── Pumps / fans ─────────────────────────────────────────────────────────
    {
        "name": "5V Mini Peristaltic Pump",
        "category": "pump",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.adafruit.com/product/1150",
        "arduino_library": "",
        "supply_voltage": [5.0],
        "current_draw_mA": 500.0,
        "description": "Small 5 V peristaltic pump for fluid / reagent handling.",
    },
    {
        "name": "4010 Cooling Fan",
        "category": "fan",
        "protocol": "PWM",
        "address": None,
        "datasheet_url": "https://www.sunon.com/uploads/files/product/4010.pdf",
        "arduino_library": "",
        "supply_voltage": [5.0, 12.0],
        "current_draw_mA": 200.0,
        "description": "40×40×10 mm axial cooling fan with PWM speed control.",
    },
    # ── Linear actuators ─────────────────────────────────────────────────────
    {
        "name": "Micro Linear Actuator",
        "category": "linear_actuator",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://www.actuonix.com/L12-R-Linear-Actuator-with-Position-Feedback-p/l12-r.htm",
        "arduino_library": "",
        "supply_voltage": [6.0, 12.0],
        "current_draw_mA": 800.0,
        "description": "Miniature 12 V linear actuator with built-in feedback potentiometer.",
    },
]


def lookup_actuator(name: str) -> dict[str, Any] | None:
    """Return the actuator entry matching *name* (case-insensitive), or None."""
    name_lower = name.lower()
    for a in ACTUATORS:
        if a["name"].lower() == name_lower:
            return a
    return None
