"""kerf_firmware.catalogue.sensors — Embedded sensor catalogue (40+ entries).

Each entry is a dict with:
  name              str   — unique part name / model identifier
  category          str   — e.g. "temperature", "imu", "distance", "gas", …
  protocol          str   — primary bus: "I2C", "SPI", "UART", "OneWire", "Analog", "GPIO"
  address           int|None  — default I2C address (7-bit), None for non-I2C parts
  datasheet_url     str   — canonical datasheet URL
  arduino_library   str   — primary Arduino/PlatformIO library name
  supply_voltage    list[float]  — acceptable VCC values in volts
  current_draw_mA   float — typical current draw in milliamps
  description       str   — one-line plain-English description
"""
from __future__ import annotations

from typing import Any

SENSORS: list[dict[str, Any]] = [
    # ── Temperature / Humidity ────────────────────────────────────────────────
    {
        "name": "DHT22",
        "category": "temperature_humidity",
        "protocol": "OneWire",
        "address": None,
        "datasheet_url": "https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf",
        "arduino_library": "DHT sensor library",
        "supply_voltage": [3.3, 5.0],
        "current_draw_mA": 1.5,
        "description": "Single-wire digital temperature and humidity sensor (±0.5 °C, ±2 %RH).",
    },
    {
        "name": "DHT11",
        "category": "temperature_humidity",
        "protocol": "OneWire",
        "address": None,
        "datasheet_url": "https://www.mouser.com/datasheet/2/758/DHT11-Technical-Data-Sheet-Translated-Version-1143054.pdf",
        "arduino_library": "DHT sensor library",
        "supply_voltage": [3.3, 5.0],
        "current_draw_mA": 0.5,
        "description": "Low-cost single-wire digital temperature and humidity sensor.",
    },
    {
        "name": "BME280",
        "category": "temperature_humidity_pressure",
        "protocol": "I2C",
        "address": 0x76,
        "datasheet_url": "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme280-ds002.pdf",
        "arduino_library": "Adafruit BME280 Library",
        "supply_voltage": [1.8, 3.3],
        "current_draw_mA": 0.714,
        "description": "Combined temperature, humidity, and barometric pressure sensor from Bosch.",
    },
    {
        "name": "BMP180",
        "category": "temperature_pressure",
        "protocol": "I2C",
        "address": 0x77,
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/BST-BMP180-DS000-09.pdf",
        "arduino_library": "Adafruit BMP085 Library",
        "supply_voltage": [1.8, 3.6],
        "current_draw_mA": 0.65,
        "description": "High-accuracy barometric pressure and temperature sensor.",
    },
    {
        "name": "BMP388",
        "category": "temperature_pressure",
        "protocol": "I2C",
        "address": 0x76,
        "datasheet_url": "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmp388-ds001.pdf",
        "arduino_library": "Adafruit BMP3XX Library",
        "supply_voltage": [1.65, 3.6],
        "current_draw_mA": 0.7,
        "description": "High-precision barometric pressure sensor with low power consumption.",
    },
    {
        "name": "SHT31",
        "category": "temperature_humidity",
        "protocol": "I2C",
        "address": 0x44,
        "datasheet_url": "https://sensirion.com/media/documents/213E6A3B/63A5A569/Datasheet_SHT3x_DIS.pdf",
        "arduino_library": "Adafruit SHT31 Library",
        "supply_voltage": [2.4, 5.5],
        "current_draw_mA": 0.6,
        "description": "High-accuracy digital temperature and humidity sensor from Sensirion.",
    },
    {
        "name": "DS18B20",
        "category": "temperature",
        "protocol": "OneWire",
        "address": None,
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf",
        "arduino_library": "DallasTemperature",
        "supply_voltage": [3.0, 5.5],
        "current_draw_mA": 1.5,
        "description": "Waterproof 1-Wire digital thermometer with ±0.5 °C accuracy.",
    },
    # ── IMU / Motion ─────────────────────────────────────────────────────────
    {
        "name": "MPU6050",
        "category": "imu",
        "protocol": "I2C",
        "address": 0x68,
        "datasheet_url": "https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf",
        "arduino_library": "Adafruit MPU6050",
        "supply_voltage": [2.375, 3.46],
        "current_draw_mA": 3.9,
        "description": "6-axis IMU with 3-axis gyroscope and accelerometer (InvenSense).",
    },
    {
        "name": "MPU9250",
        "category": "imu",
        "protocol": "I2C",
        "address": 0x68,
        "datasheet_url": "https://invensense.tdk.com/wp-content/uploads/2015/02/PS-MPU-9250A-01-v1.1.pdf",
        "arduino_library": "MPU9250",
        "supply_voltage": [2.4, 3.6],
        "current_draw_mA": 3.7,
        "description": "9-axis IMU with gyroscope, accelerometer, and magnetometer.",
    },
    {
        "name": "LSM6DS3",
        "category": "imu",
        "protocol": "I2C",
        "address": 0x6A,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/lsm6ds3.pdf",
        "arduino_library": "Arduino_LSM6DS3",
        "supply_voltage": [1.71, 3.6],
        "current_draw_mA": 0.9,
        "description": "Low-power 6-axis iNEMO inertial module (ST Microelectronics).",
    },
    {
        "name": "ICM-20948",
        "category": "imu",
        "protocol": "I2C",
        "address": 0x68,
        "datasheet_url": "https://invensense.tdk.com/wp-content/uploads/2016/06/DS-000189-ICM-20948-v1.3.pdf",
        "arduino_library": "SparkFun ICM-20948 IMU",
        "supply_voltage": [1.71, 1.89],
        "current_draw_mA": 2.5,
        "description": "World's lowest power 9-axis MEMS motion tracking device.",
    },
    {
        "name": "ADXL345",
        "category": "accelerometer",
        "protocol": "I2C",
        "address": 0x53,
        "datasheet_url": "https://www.analog.com/media/en/technical-documentation/data-sheets/adxl345.pdf",
        "arduino_library": "Adafruit ADXL345",
        "supply_voltage": [2.0, 3.6],
        "current_draw_mA": 0.14,
        "description": "Low-power 3-axis ±16g digital accelerometer with SPI/I2C.",
    },
    {
        "name": "HMC5883L",
        "category": "magnetometer",
        "protocol": "I2C",
        "address": 0x1E,
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/HMC5883L_3-Axis_Digital_Compass_IC.pdf",
        "arduino_library": "Adafruit HMC5883 Unified",
        "supply_voltage": [2.16, 3.6],
        "current_draw_mA": 0.1,
        "description": "3-axis digital compass / magnetometer.",
    },
    # ── Distance / Proximity ─────────────────────────────────────────────────
    {
        "name": "VL53L0X",
        "category": "distance",
        "protocol": "I2C",
        "address": 0x29,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/vl53l0x.pdf",
        "arduino_library": "VL53L0X",
        "supply_voltage": [2.6, 3.5],
        "current_draw_mA": 19.0,
        "description": "Time-of-flight laser distance sensor, range up to 2 m (ST).",
    },
    {
        "name": "VL53L1X",
        "category": "distance",
        "protocol": "I2C",
        "address": 0x29,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/vl53l1x.pdf",
        "arduino_library": "SparkFun VL53L1X 4m Laser Distance Sensor",
        "supply_voltage": [2.6, 3.5],
        "current_draw_mA": 22.0,
        "description": "Long-range time-of-flight sensor, up to 4 m.",
    },
    {
        "name": "HC-SR04",
        "category": "distance",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://cdn.sparkfun.com/datasheets/Sensors/Proximity/HCSR04.pdf",
        "arduino_library": "HCSR04",
        "supply_voltage": [5.0],
        "current_draw_mA": 15.0,
        "description": "Ultrasonic distance sensor, 2 cm to 400 cm range.",
    },
    {
        "name": "APDS-9960",
        "category": "gesture_proximity_color",
        "protocol": "I2C",
        "address": 0x39,
        "datasheet_url": "https://cdn.sparkfun.com/assets/learn_tutorials/3/2/1/Avago-APDS-9960-datasheet.pdf",
        "arduino_library": "SparkFun APDS-9960 RGB and Gesture Sensor",
        "supply_voltage": [2.4, 3.6],
        "current_draw_mA": 1.0,
        "description": "RGB, ambient light, proximity, and gesture sensor.",
    },
    # ── Biometric ────────────────────────────────────────────────────────────
    {
        "name": "MAX30102",
        "category": "biometric",
        "protocol": "I2C",
        "address": 0x57,
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/MAX30102.pdf",
        "arduino_library": "SparkFun MAX3010x Pulse and Proximity Sensor Library",
        "supply_voltage": [1.8],
        "current_draw_mA": 0.7,
        "description": "Pulse oximetry and heart-rate monitor sensor module.",
    },
    {
        "name": "MAX30205",
        "category": "biometric",
        "protocol": "I2C",
        "address": 0x48,
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/MAX30205.pdf",
        "arduino_library": "Protocentral MAX30205 Human Body Temperature Sensor",
        "supply_voltage": [2.7, 3.3],
        "current_draw_mA": 0.6,
        "description": "Human body temperature sensor with ±0.1 °C accuracy.",
    },
    # ── Gas / Air Quality ─────────────────────────────────────────────────────
    {
        "name": "MQ-2",
        "category": "gas",
        "protocol": "Analog",
        "address": None,
        "datasheet_url": "https://www.parallax.com/sites/default/files/downloads/605-00008-MQ-2-Datasheet.pdf",
        "arduino_library": "MQUnifiedsensor",
        "supply_voltage": [5.0],
        "current_draw_mA": 150.0,
        "description": "Flammable gas / smoke sensor (LPG, propane, hydrogen, methane).",
    },
    {
        "name": "CCS811",
        "category": "air_quality",
        "protocol": "I2C",
        "address": 0x5A,
        "datasheet_url": "https://cdn.sparkfun.com/assets/learn_tutorials/1/4/3/CCS811_Datasheet-DS000459.pdf",
        "arduino_library": "SparkFun CCS811 Arduino Library",
        "supply_voltage": [1.8, 3.3],
        "current_draw_mA": 26.0,
        "description": "Ultra-low power CO2 equivalent and TVOC air quality sensor.",
    },
    {
        "name": "SGP30",
        "category": "air_quality",
        "protocol": "I2C",
        "address": 0x58,
        "datasheet_url": "https://sensirion.com/media/documents/984E0DD5/61644B8B/Sensirion_Gas_Sensors_Datasheet_SGP30.pdf",
        "arduino_library": "Adafruit SGP30 Gas / Air Quality Sensor Library",
        "supply_voltage": [1.62, 1.98],
        "current_draw_mA": 48.8,
        "description": "Multi-pixel gas sensor for indoor air quality (TVOC + eCO2).",
    },
    {
        "name": "BME680",
        "category": "air_quality_environment",
        "protocol": "I2C",
        "address": 0x76,
        "datasheet_url": "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme680-ds001.pdf",
        "arduino_library": "Adafruit BME680 Library",
        "supply_voltage": [1.71, 3.6],
        "current_draw_mA": 0.9,
        "description": "4-in-1 environmental sensor: gas, humidity, temperature, pressure.",
    },
    # ── Light ────────────────────────────────────────────────────────────────
    {
        "name": "TSL2591",
        "category": "light",
        "protocol": "I2C",
        "address": 0x29,
        "datasheet_url": "https://ams.com/documents/20143/36005/TSL2591_DS000338_6-00.pdf",
        "arduino_library": "Adafruit TSL2591 Library",
        "supply_voltage": [3.3, 5.0],
        "current_draw_mA": 0.6,
        "description": "High dynamic range digital light sensor (600,000,000:1 range).",
    },
    {
        "name": "BH1750",
        "category": "light",
        "protocol": "I2C",
        "address": 0x23,
        "datasheet_url": "https://www.mouser.com/datasheet/2/348/bh1750fvi-e-186247.pdf",
        "arduino_library": "BH1750",
        "supply_voltage": [2.4, 3.6],
        "current_draw_mA": 0.12,
        "description": "16-bit digital ambient light sensor in lux.",
    },
    # ── GPS / GNSS ────────────────────────────────────────────────────────────
    {
        "name": "NEO-6M",
        "category": "gps",
        "protocol": "UART",
        "address": None,
        "datasheet_url": "https://www.u-blox.com/sites/default/files/products/documents/NEO-6_DataSheet_(GPS.G6-HW-09005).pdf",
        "arduino_library": "TinyGPS++",
        "supply_voltage": [2.7, 3.6],
        "current_draw_mA": 37.0,
        "description": "u-blox NEO-6M GPS module with UART interface.",
    },
    {
        "name": "NEO-M8N",
        "category": "gps",
        "protocol": "UART",
        "address": None,
        "datasheet_url": "https://www.u-blox.com/sites/default/files/NEO-M8_DataSheet_%28UBX-13003366%29.pdf",
        "arduino_library": "TinyGPS++",
        "supply_voltage": [1.71, 1.89],
        "current_draw_mA": 29.0,
        "description": "High-performance M8 GNSS module (GPS/GLONASS/Galileo/BeiDou).",
    },
    # ── Current / Voltage ─────────────────────────────────────────────────────
    {
        "name": "INA219",
        "category": "current_voltage",
        "protocol": "I2C",
        "address": 0x40,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/ina219.pdf",
        "arduino_library": "Adafruit INA219",
        "supply_voltage": [3.0, 5.5],
        "current_draw_mA": 0.7,
        "description": "High-side DC current sensor with I2C (±26 V, 3.2 A full-scale).",
    },
    {
        "name": "INA3221",
        "category": "current_voltage",
        "protocol": "I2C",
        "address": 0x40,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/ina3221.pdf",
        "arduino_library": "INA3221",
        "supply_voltage": [2.7, 5.5],
        "current_draw_mA": 0.35,
        "description": "Three-channel current/voltage monitor over I2C.",
    },
    # ── Colour ────────────────────────────────────────────────────────────────
    {
        "name": "TCS34725",
        "category": "color",
        "protocol": "I2C",
        "address": 0x29,
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/TCS34725.pdf",
        "arduino_library": "Adafruit TCS34725",
        "supply_voltage": [2.7, 3.6],
        "current_draw_mA": 0.65,
        "description": "RGB colour light-to-digital converter with IR blocking filter.",
    },
    # ── Soil / Moisture ───────────────────────────────────────────────────────
    {
        "name": "Capacitive Soil Moisture v2.0",
        "category": "moisture",
        "protocol": "Analog",
        "address": None,
        "datasheet_url": "https://wiki.dfrobot.com/Capacitive_Soil_Moisture_Sensor_SKU_SEN0193",
        "arduino_library": "",
        "supply_voltage": [3.3, 5.0],
        "current_draw_mA": 5.0,
        "description": "Capacitive soil moisture sensor (corrosion-resistant, no exposed contacts).",
    },
    # ── Sound / Audio ─────────────────────────────────────────────────────────
    {
        "name": "MAX4466",
        "category": "sound",
        "protocol": "Analog",
        "address": None,
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/MAX4465-MAX4469.pdf",
        "arduino_library": "",
        "supply_voltage": [2.7, 5.5],
        "current_draw_mA": 24.0,
        "description": "Adjustable-gain electret microphone amplifier.",
    },
    {
        "name": "INMP441",
        "category": "sound",
        "protocol": "I2S",
        "address": None,
        "datasheet_url": "https://www.invensense.tdk.com/wp-content/uploads/2015/02/INMP441.pdf",
        "arduino_library": "ESP-IDF I2S",
        "supply_voltage": [1.8, 3.3],
        "current_draw_mA": 1.4,
        "description": "High-performance, low-power, I2S MEMS microphone.",
    },
    # ── Flex / Force ─────────────────────────────────────────────────────────
    {
        "name": "FSR402",
        "category": "force",
        "protocol": "Analog",
        "address": None,
        "datasheet_url": "https://www.sparkfun.com/datasheets/Sensors/Pressure/fsrguide.pdf",
        "arduino_library": "",
        "supply_voltage": [3.3, 5.0],
        "current_draw_mA": 1.0,
        "description": "Force-sensitive resistor (0.1–10 N range, 0.5 cm diameter).",
    },
    # ── Magnetic / Hall ───────────────────────────────────────────────────────
    {
        "name": "ACS712",
        "category": "current",
        "protocol": "Analog",
        "address": None,
        "datasheet_url": "https://www.allegromicro.com/~/media/Files/Datasheets/ACS712-Datasheet.ashx",
        "arduino_library": "ACS712",
        "supply_voltage": [4.5, 5.5],
        "current_draw_mA": 13.0,
        "description": "Fully integrated Hall-effect current sensor (±5 A / ±20 A / ±30 A).",
    },
    {
        "name": "AS5600",
        "category": "magnetic_encoder",
        "protocol": "I2C",
        "address": 0x36,
        "datasheet_url": "https://ams.com/documents/20143/36005/AS5600_DS000365_5-00.pdf",
        "arduino_library": "AS5600",
        "supply_voltage": [3.0, 3.6],
        "current_draw_mA": 6.5,
        "description": "Easy-to-use magnetic rotary position sensor (12-bit resolution).",
    },
    # ── Camera / Imaging ─────────────────────────────────────────────────────
    {
        "name": "OV2640",
        "category": "camera",
        "protocol": "SPI",
        "address": None,
        "datasheet_url": "https://www.uctronics.com/download/cam_module/OV2640DS.pdf",
        "arduino_library": "esp32-camera",
        "supply_voltage": [3.3],
        "current_draw_mA": 60.0,
        "description": "2MP CMOS image sensor used on ESP32-CAM modules.",
    },
    # ── Touch ─────────────────────────────────────────────────────────────────
    {
        "name": "MPR121",
        "category": "touch",
        "protocol": "I2C",
        "address": 0x5A,
        "datasheet_url": "https://www.nxp.com/docs/en/data-sheet/MPR121.pdf",
        "arduino_library": "Adafruit MPR121",
        "supply_voltage": [1.71, 3.6],
        "current_draw_mA": 29.0,
        "description": "12-channel capacitive touch sensor controller.",
    },
    # ── CO2 ───────────────────────────────────────────────────────────────────
    {
        "name": "MH-Z19B",
        "category": "co2",
        "protocol": "UART",
        "address": None,
        "datasheet_url": "https://www.winsen-sensor.com/d/files/MH-Z19B.pdf",
        "arduino_library": "MHZ19",
        "supply_voltage": [4.5, 5.5],
        "current_draw_mA": 125.0,
        "description": "NDIR CO2 sensor module, 0–5000 ppm range.",
    },
    {
        "name": "SCD40",
        "category": "co2",
        "protocol": "I2C",
        "address": 0x62,
        "datasheet_url": "https://sensirion.com/media/documents/48C4B7FB/64C134E7/Sensirion_SCD4x_Datasheet.pdf",
        "arduino_library": "Sensirion I2C SCD4x",
        "supply_voltage": [2.4, 5.5],
        "current_draw_mA": 18.0,
        "description": "Photoacoustic CO2, temperature, humidity sensor (Sensirion).",
    },
    # ── Load Cell ────────────────────────────────────────────────────────────
    {
        "name": "HX711",
        "category": "load_cell_adc",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://cdn.sparkfun.com/datasheets/Sensors/ForceFlex/hx711_english.pdf",
        "arduino_library": "HX711",
        "supply_voltage": [2.6, 5.5],
        "current_draw_mA": 1.5,
        "description": "24-bit ADC amplifier for load cell / Wheatstone bridge.",
    },
    # ── Radar ─────────────────────────────────────────────────────────────────
    {
        "name": "RCWL-0516",
        "category": "radar",
        "protocol": "GPIO",
        "address": None,
        "datasheet_url": "https://github.com/jdesbonnet/RCWL-0516/blob/master/extras/RCWL-0516-A.1-001%20v1.pdf",
        "arduino_library": "",
        "supply_voltage": [4.0, 28.0],
        "current_draw_mA": 3.0,
        "description": "Microwave Doppler radar motion detector module.",
    },
    # ── RFID / NFC ────────────────────────────────────────────────────────────
    {
        "name": "MFRC522",
        "category": "rfid",
        "protocol": "SPI",
        "address": None,
        "datasheet_url": "https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf",
        "arduino_library": "MFRC522",
        "supply_voltage": [2.5, 3.3],
        "current_draw_mA": 13.0,
        "description": "13.56 MHz RFID reader/writer IC (ISO 14443A/MIFARE).",
    },
    {
        "name": "PN532",
        "category": "nfc",
        "protocol": "I2C",
        "address": 0x24,
        "datasheet_url": "https://www.nxp.com/docs/en/user-guide/141520.pdf",
        "arduino_library": "Adafruit PN532",
        "supply_voltage": [3.3, 5.0],
        "current_draw_mA": 150.0,
        "description": "NFC controller supporting ISO 14443A/B, Felica, read/write.",
    },
]


def lookup_sensor(name: str) -> dict[str, Any] | None:
    """Return the sensor entry matching *name* (case-insensitive), or None."""
    name_lower = name.lower()
    for s in SENSORS:
        if s["name"].lower() == name_lower:
            return s
    return None
