"""DO-254 Markdown template generator.

Each template follows the section structure mandated by RTCA DO-254
(2000) and FAA AC 20-152 / EASA AMC 20-152A.

``[FILL IN]`` marks every field the hardware engineer must complete;
project-level fields are substituted from *project_meta* when provided.

Minimum *project_meta* keys (all optional; missing keys remain as
``[FILL IN]``):
    project_name   str  Human-readable hardware component name
    dal            str  Design Assurance Level letter, e.g. ``"B"``
    aircraft_type  str  Platform / aircraft type
    applicant      str  Organisation submitting for certification
    date           str  Document date (ISO-8601 recommended)
    version        str  Document version / revision identifier
    author         str  Primary author name or team
    der            str  Designated Engineering Representative name
    hardware_type  str  e.g. ``"FPGA"`` / ``"ASIC"`` / ``"PCB"``
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Public constant
# ---------------------------------------------------------------------------

SUPPORTED_DOC_TYPES: tuple[str, ...] = (
    "PHAC",
    "HDP",
    "HVVP",
    "HPAP",
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _sub(template: str, meta: dict[str, Any]) -> str:
    """Substitute *meta* values into *template*."""
    import re

    def _replace(m: "re.Match[str]") -> str:
        key = m.group(1).strip()
        return str(meta.get(key, "[FILL IN]"))

    return re.sub(r"\{\{(\w+)\}\}", _replace, template)


_HEADER = """\
<!-- DO-254 Certification Artefact — generated by kerf-aero -->
<!-- Applicant must review, complete all [FILL IN] fields, and obtain DER review before submission. -->

# {{doc_type_title}}

**Project:** {{project_name}}
**Hardware Type:** {{hardware_type}}
**DAL:** {{dal}}
**Aircraft / Platform:** {{aircraft_type}}
**Applicant:** {{applicant}}
**Document Version:** {{version}}
**Date:** {{date}}
**Author:** {{author}}
**DER:** {{der}}

---
"""


# ---------------------------------------------------------------------------
# Individual document templates
# ---------------------------------------------------------------------------

_PHAC = (
    _HEADER
    + """\
## 1  System Overview

### 1.1  System Description

[FILL IN — Describe the airborne system in which this hardware component
operates, its operational context, and mission-critical functions.]

### 1.2  Hardware Overview

[FILL IN — Describe the hardware item: type ({{hardware_type}}),
technology family, gate count / complexity, operating environment
(temperature, vibration, EMI), and life expectancy.]

### 1.3  Hardware Function

[FILL IN — List the functions this hardware item performs, including
any safety-critical control, monitoring, or protection roles.]

---

## 2  Certification Basis

### 2.1  Applicable Regulations

[FILL IN — e.g., 14 CFR Part 25 / Part 23; EASA CS-25 / CS-23;
applicable amendment level; applicable special conditions.]

### 2.2  Means of Compliance

[FILL IN — Reference AC 20-152 / EASA AMC 20-152A.  Identify whether
the guidance is followed in full or with agreed-upon alternative means.]

### 2.3  Design Assurance Level

Hardware DAL: **{{dal}}** — [FILL IN — failure condition category and
effect per ARP 4761 / AC 25.1309.]

---

## 3  Hardware Life-Cycle

### 3.1  Life-Cycle Processes

[FILL IN — Planning, requirements capture, conceptual design, detailed
design, implementation, production transition, V&V, CM, process
assurance, and certification liaison.]

### 3.2  Development Environment

| Item | Description |
|------|-------------|
| HDL language | [FILL IN — VHDL / Verilog / SystemVerilog] |
| Synthesis tool | [FILL IN] |
| P&R tool | [FILL IN] |
| Simulation tool | [FILL IN] |
| Formal verification | [FILL IN — if applicable] |
| FPGA family / foundry PDK | [FILL IN] |
| PCB CAD tool | [FILL IN — if applicable] |
| Version control | [FILL IN] |

---

## 4  Hardware Requirements

### 4.1  Derived Requirements

[FILL IN — Identify any hardware requirements derived from the design
that must be fed back to the system safety assessment process per
DO-254 §5.2.]

### 4.2  Requirements Allocation

[FILL IN — Describe how system requirements are allocated to this
hardware item and how derived requirements are tracked.]

---

## 5  Certification Coordination

### 5.1  Stage of Involvement Plan

| SOI | Phase | Planned Date |
|-----|-------|--------------|
| 1   | Planning review | [FILL IN] |
| 2   | Design review | [FILL IN] |
| 3   | Verification review | [FILL IN] |
| 4   | Final compliance determination | [FILL IN] |

### 5.2  Certification Authority Interface

[FILL IN — Describe the planned interaction with the certification
authority: initial meeting, interim reviews, and the final compliance
finding activity.]

---

## 6  Hardware Life-Cycle Data

### 6.1  Required Artefacts for DAL {{dal}}

[FILL IN — List all hardware life-cycle data items per DO-254 Table A-1
applicable to DAL {{dal}}.  Reference `required_artefacts_do254("{{dal}}")`.]

### 6.2  Data Control Categories

| Artefact | CC1 / CC2 | Location |
|----------|-----------|----------|
| PHAC     | CC2 | [FILL IN] |
| HDP      | CC2 | [FILL IN] |
| HVVP     | CC2 | [FILL IN] |
| HPAP     | CC2 | [FILL IN] |
| HRD      | CC2 | [FILL IN] |
| HDD      | CC1 | [FILL IN] |
| HDL Source | CC1 | [FILL IN] |
| Verification Results | CC1 | [FILL IN] |
| HAS      | CC2 | [FILL IN] |

---

## 7  Tool Assessment

[FILL IN — Identify any design or verification tools used on this
project, assess their output correctness risk, and describe the
tool-assessment or qualification approach per DO-254 §11.4.]

---

## 8  Previously Developed Hardware

[FILL IN — Identify any reused IP blocks, COTS hardware, or legacy
designs, and describe the credit sought and gap analysis performed.]

---

## 9  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of PHAC*
"""
)

_HDP = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This Hardware Development Plan (HDP) defines the development processes
and standards for **{{project_name}}** ({{hardware_type}}, DAL {{dal}}).

### 1.2  Scope

[FILL IN — Describe the hardware item covered by this plan.]

### 1.3  Reference Documents

| Reference | Title |
|-----------|-------|
| RTCA DO-254 | Design Assurance Guidance for Airborne Electronic Hardware |
| FAA AC 20-152 | RTCA Inc. Document RTCA/DO-254 |
| PHAC | Plan for Hardware Aspects of Certification |
| [FILL IN] | System Requirements Specification |

---

## 2  Hardware Development Environment

### 2.1  HDL and Coding Standards

- **HDL Language:** [FILL IN — VHDL / Verilog / SystemVerilog]
- **Language Standard:** [FILL IN — e.g., VHDL-2008, SystemVerilog IEEE 1800-2017]
- **Coding Guidelines:** [FILL IN — e.g., STARC VHDL Guidelines, internal checklist]
- **Lint / Static Analysis Tool:** [FILL IN]

### 2.2  EDA Toolchain

| Tool | Function | Version | Assessment Status |
|------|----------|---------|-------------------|
| [FILL IN] | RTL Synthesis | [FILL IN] | [FILL IN] |
| [FILL IN] | Place and Route | [FILL IN] | [FILL IN] |
| [FILL IN] | Timing Analysis | [FILL IN] | [FILL IN] |
| [FILL IN] | Simulation | [FILL IN] | [FILL IN] |
| [FILL IN] | Formal Verification | [FILL IN] | [FILL IN — if applicable] |

### 2.3  Target Device / Technology

| Item | Value |
|------|-------|
| Device family | [FILL IN] |
| Process node / foundry | [FILL IN] |
| Logic elements / cell count | [FILL IN] |
| On-chip memory | [FILL IN] |
| I/O standard | [FILL IN] |

---

## 3  Requirements Process

### 3.1  Hardware Requirements Capture

[FILL IN — Describe the process for capturing hardware requirements from
system requirements: review, traceability tagging, and derived-requirement
identification.]

### 3.2  Derived Requirements Feedback

[FILL IN — Describe how hardware-derived requirements are communicated
back to the system safety assessment in accordance with DO-254 §5.2.]

---

## 4  Conceptual Design Process

[FILL IN — Describe the top-level architectural design activities:
block diagram, major sub-function partitioning, clocking strategy,
reset strategy, and preliminary timing budget.]

---

## 5  Detailed Design Process

### 5.1  RTL Design

[FILL IN — Describe RTL coding, module hierarchy, and the review
gates before synthesis.]

### 5.2  Synthesis and Constraints

[FILL IN — Describe the synthesis flow, timing constraints (SDC / XDC),
and how timing closure is achieved and verified.]

### 5.3  Place and Route

[FILL IN — Describe the P&R flow, floorplanning strategy, and final
timing sign-off criteria.]

### 5.4  Bitstream / GDSII Generation

[FILL IN — Describe the final implementation step, bitstream security
settings (for FPGA), or tape-out submission process (for ASIC).]

---

## 6  Integration Process

[FILL IN — Describe how the hardware item integrates with the broader
system: bench integration, bring-up procedure, and hardware / software
co-verification approach.]

---

## 7  Traceability

[FILL IN — Describe the requirements-traceability discipline from system
requirements through HRD to conceptual design to RTL modules to test
cases.  Reference the kerf-aero `.req.json` / `.test.json` scaffolding.]

---

## 8  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of HDP*
"""
)

_HVVP = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This Hardware Verification and Validation Plan (HVVP) describes the V&V
activities for **{{project_name}}** ({{hardware_type}}, DAL {{dal}}).

### 1.2  Scope

[FILL IN — Identify the hardware life-cycle data items subject to
verification.]

### 1.3  Reference Documents

| Reference | Title |
|-----------|-------|
| RTCA DO-254 | Design Assurance Guidance for Airborne Electronic Hardware |
| HDP | Hardware Development Plan |
| HRD | Hardware Requirements Document |

---

## 2  Verification Environment

### 2.1  Simulation Environment

| Item | Description |
|------|-------------|
| Simulator | [FILL IN] |
| Version | [FILL IN] |
| Testbench language | [FILL IN — e.g., SystemVerilog UVM, VHDL, Python/cocotb] |
| Randomisation seed policy | [FILL IN] |

### 2.2  Formal Verification Environment

[FILL IN — If formal methods (model checking, equivalence checking) are
used, describe the tool, property language, and scope of formal proofs.]

### 2.3  Hardware-in-the-Loop / Bench Test Environment

[FILL IN — Describe the test bench hardware (FPGA prototyping board,
emulation platform, or target system), measurement equipment, and
calibration records.]

---

## 3  Verification of Hardware Requirements

### 3.1  Review

[FILL IN — Describe the process for reviewing hardware requirements for
correctness, consistency, verifiability, and completeness.]

### 3.2  Functional Simulation Tests

[FILL IN — Describe the simulation test strategy: directed tests, random
tests, boundary-value analysis, and coverage closure plan.]

### 3.3  Requirements Coverage

[FILL IN — Describe how 100 % of hardware requirements are mapped to at
least one verification activity (test, analysis, inspection, or
demonstration).]

---

## 4  Verification of Hardware Design

### 4.1  RTL Reviews

[FILL IN — Describe the RTL code-review process: review checklist,
tool-assisted lint, and synthesis-for-test dry-run.]

### 4.2  Timing Analysis

[FILL IN — Describe the static timing analysis (STA) flow, worst-case
timing margins, and acceptable timing-violation disposition process.]

### 4.3  Equivalence Checking

[FILL IN — Describe the RTL-vs-netlist equivalence check (if used) and
the acceptable result criteria.]

---

## 5  Elemental Analysis (DAL A/B)

[FILL IN — For DAL A and B, describe the elemental analysis performed
to show that the design is free of unintended functions.  Reference
the specific DO-254 §6.2 activities planned.]

---

## 6  Validation

### 6.1  Bench / System Validation

[FILL IN — Describe how the hardware item is validated in the target
system environment, including the acceptance test procedure and the
pass/fail criteria.]

### 6.2  Environmental Qualification

[FILL IN — Reference any DO-160 environmental qualification testing
(temperature, vibration, EMI/EMC) planned or completed for this item.]

---

## 7  Independence

[FILL IN — Describe the verification independence required for DAL {{dal}}
per DO-254 §9.4 and how it is achieved.]

---

## 8  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of HVVP*
"""
)

_HPAP = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This Hardware Process Assurance Plan (HPAP) defines the process
assurance activities for **{{project_name}}** ({{hardware_type}}, DAL {{dal}}).

### 1.2  Scope

[FILL IN — Identify the life-cycle processes and artefacts subject to
process assurance oversight.]

### 1.3  Reference Documents

| Reference | Title |
|-----------|-------|
| RTCA DO-254 | Design Assurance Guidance for Airborne Electronic Hardware |
| PHAC | Plan for Hardware Aspects of Certification |
| HDP | Hardware Development Plan |
| HVVP | Hardware Verification and Validation Plan |

---

## 2  Hardware Process Assurance Organisation

### 2.1  HPA Authority and Independence

[FILL IN — Describe the HPA function's independence from the hardware
development team and its authority to flag non-compliances to management
and the certification authority.]

### 2.2  Responsibilities

| Role | Responsibility |
|------|----------------|
| HPA Lead | [FILL IN] |
| Hardware Lead | [FILL IN] |
| Project Manager | [FILL IN] |

---

## 3  Process Assurance Activities

### 3.1  Plan Compliance Reviews

[FILL IN — Schedule and scope of reviews to verify that the project is
executing per PHAC, HDP, HVVP, and any additional plans.]

| Review | Life-Cycle Phase | Planned Date |
|--------|-----------------|--------------|
| HPA-R01 | Planning complete | [FILL IN] |
| HPA-R02 | Conceptual design complete | [FILL IN] |
| HPA-R03 | Detailed design complete | [FILL IN] |
| HPA-R04 | Verification complete | [FILL IN] |
| HPA-R05 | Pre-submission | [FILL IN] |

### 3.2  Transition Criteria Audits

[FILL IN — Describe the entrance/exit criteria checks at each phase
transition and how HPA signs off before the next phase begins.]

### 3.3  Spot Audits

[FILL IN — Describe the unannounced spot-audit approach: frequency,
scope selection, and reporting.]

---

## 4  Conformity Review

### 4.1  Functional Configuration Audit (FCA)

[FILL IN — Describe the FCA scope, the artefacts reviewed, and the
criteria for a satisfactory outcome.]

### 4.2  Physical Configuration Audit (PCA)

[FILL IN — Describe the PCA scope (as-built vs. design data), the
criteria for acceptance, and the process for resolving discrepancies.]

---

## 5  Non-Conformance Management

### 5.1  Identification and Recording

[FILL IN — Describe how process non-conformances are captured, classified
(minor / major / critical), and linked to problem reports.]

### 5.2  Disposition and Closure Verification

[FILL IN — Describe the approval chain for disposition, the corrective-
action timeline, and HPA verification of closure.]

---

## 6  HPA Records

[FILL IN — List the HPA records retained, their location, and the
retention period (typically life-of-type + 10 years).]

---

## 7  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of HPAP*
"""
)


# ---------------------------------------------------------------------------
# Mapping and public API
# ---------------------------------------------------------------------------

_TEMPLATES: dict[str, str] = {
    "PHAC": _PHAC,
    "HDP": _HDP,
    "HVVP": _HVVP,
    "HPAP": _HPAP,
}

_DOC_TITLES: dict[str, str] = {
    "PHAC": "Plan for Hardware Aspects of Certification (PHAC)",
    "HDP": "Hardware Development Plan (HDP)",
    "HVVP": "Hardware Verification and Validation Plan (HVVP)",
    "HPAP": "Hardware Process Assurance Plan (HPAP)",
}


def generate_template(doc_type: str, project_meta: dict[str, Any] | None = None) -> str:
    """Return a Markdown skeleton for *doc_type* with placeholders filled.

    Parameters
    ----------
    doc_type:
        One of ``SUPPORTED_DOC_TYPES`` (e.g. ``"PHAC"``, ``"HDP"``).
        Case-insensitive.
    project_meta:
        Optional dict of project-level values.  Recognised keys:
        ``project_name``, ``dal``, ``aircraft_type``, ``applicant``,
        ``version``, ``date``, ``author``, ``der``, ``hardware_type``.
        Unknown keys are ignored.  Missing keys produce ``[FILL IN]``.

    Returns
    -------
    str
        Markdown document with ``[FILL IN]`` placeholders for any
        project-meta fields not supplied.

    Raises
    ------
    ValueError
        If *doc_type* is not in ``SUPPORTED_DOC_TYPES``.
    """
    key = doc_type.strip().upper()
    if key not in _TEMPLATES:
        valid = ", ".join(SUPPORTED_DOC_TYPES)
        raise ValueError(
            f"Unknown DO-254 doc_type {doc_type!r}. Valid values: {valid}"
        )

    meta: dict[str, Any] = dict(project_meta or {})
    meta["doc_type_title"] = _DOC_TITLES[key]
    if "dal" not in meta:
        meta["dal"] = "[FILL IN]"
    if "hardware_type" not in meta:
        meta["hardware_type"] = "[FILL IN]"

    return _sub(_TEMPLATES[key], meta)
