"""
CAM toolpath generation via OpenCAMlib.

POST /run-cam
Body: {
    "step_b64": string (base64-encoded STEP file),
    "operations": [...],
    "post_processor": string
}

Returns: {
    "g_code": string,
    "warnings": [],
    "errors": []
}
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import base64
import json
import tempfile
from pathlib import Path
from typing import Optional

router = APIRouter()


class CAMOperation(BaseModel):
    type: str
    tool_diameter: float
    step_down: float
    step_over: float
    feed_rate: float
    spindle_rpm: int
    coolant: str = "flood"


class CAMRequest(BaseModel):
    step_b64: str
    operations: list[CAMOperation]
    post_processor: str = "fanuc"


@router.post("/run-cam")
async def run_cam(req: CAMRequest):
    if not req.step_b64:
        raise HTTPException(status_code=400, detail="step_b64 required")

    try:
        step_bytes = base64.b64decode(req.step_b64)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"invalid step_b64: {e}")

    try:
        import opencamlib as ocl
    except ImportError as e:
        return {
            "g_code": "",
            "warnings": [],
            "errors": [f"opencamlib not available: {e}"],
        }

    warnings = []
    errors = []

    with tempfile.TemporaryDirectory() as tmpdir:
        step_path = Path(tmpdir) / "input.step"
        step_path.write_bytes(step_bytes)

        try:
            g_code = generate_toolpaths(str(step_path), req.operations, req.post_processor)
        except Exception as e:
            errors.append(str(e))
            g_code = ""

    return {
        "g_code": g_code,
        "warnings": warnings,
        "errors": errors,
    }


def generate_toolpaths(step_path: str, operations: list, post_processor: str) -> str:
    import opencamlib as ocl

    mid = ocl.STLObj()
    mid.readFile(step_path)

    toolpaths = []
    for op in operations:
        tool = ocl.CylCutter(op.tool_diameter / 1000.0, 0.0)
        op_type = op.type.lower()

        if op_type == "waterline":
            lw = ocl.Waterline(mid)
            lw.setTool(tool)
            lw.setSampling(op.step_over / 1000.0)
            lw.setRes(0.001)
            lw.run()
            toolpaths.append(lw.getCLPoints())

        elif op_type == "resample":
            rs = ocl.Resample()
            rs.setInput(mid)
            rs.setTool(tool)
            rs.setStepOver(op.step_over / 1000.0)
            rs.run()
            toolpaths.append(rs.getCLPoints())

        elif op_type == "adaptive":
            ad = ocl.AdaptiveCC(mid)
            ad.setTool(tool)
            ad.setStepOver(op.step_over / 1000.0)
            ad.setZ(org=0.0, target=-op.step_down / 1000.0)
            ad.setSampling(op.step_over / 1000.0)
            ad.run()
            toolpaths.append(ad.getCLPoints())

        else:
            lw = ocl.Waterline(mid)
            lw.setTool(tool)
            lw.setSampling(op.step_over / 1000.0)
            lw.setRes(0.001)
            lw.run()
            toolpaths.append(lw.getCLPoints())

    g_code = generate_g_code(toolpaths, operations, post_processor)
    return g_code


def generate_g_code(toolpaths: list, operations: list, post_processor: str) -> str:
    g_code_lines = [
        f"; Generated by pyworker CAM",
        f"; Post-processor: {post_processor}",
        "G90 G54",
        "G17",
    ]

    for i, (tp, op) in enumerate(zip(toolpaths, operations)):
        g_code_lines.append(f"; Operation {i + 1}: {op.type}")
        g_code_lines.append(f"M6 T{i + 1}")
        g_code_lines.append(f"G0 Z50.0")
        g_code_lines.append(f"S{op.spindle_rpm} M3")

        if len(tp) > 0:
            g_code_lines.append(f"X{tp[0].x * 1000:.3f} Y{tp[0].y * 1000:.3f}")
            g_code_lines.append(f"Z{tp[0].z * 1000 + 2.0:.3f}")

            for point in tp:
                g_code_lines.append(
                    f"G1 X{point.x * 1000:.3f} Y{point.y * 1000:.3f} Z{point.z * 1000:.3f} F{op.feed_rate}"
                )

        g_code_lines.append("G0 Z50.0")

    g_code_lines.append("M5")
    g_code_lines.append("M30")

    return "\n".join(g_code_lines)
