"""DO-178C Markdown template generator.

Each template follows the section structure mandated by RTCA DO-178C
(2011) and its supplements (DO-330, DO-331, DO-332, DO-333).
``[FILL IN]`` marks every field the engineer must complete; project-
level fields are substituted from *project_meta* when provided.

Minimum *project_meta* keys (all optional; missing keys remain as
``[FILL IN]``):
    project_name   str  Human-readable project / software component name
    dal            str  Design Assurance Level letter, e.g. ``"A"``
    aircraft_type  str  Platform / aircraft type
    applicant      str  Organisation submitting for certification
    date           str  Document date (ISO-8601 recommended)
    version        str  Document version / revision identifier
    author         str  Primary author name or team
    dqa            str  Designated Engineering Representative (DER) / DQA name
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Public constant — all recognised doc_type strings
# ---------------------------------------------------------------------------

SUPPORTED_DOC_TYPES: tuple[str, ...] = (
    "PSAC",
    "SDP",
    "SVP",
    "SCMP",
    "SQAP",
    "HLR",
    "LLR",
    "SDD",
    "SVCP",
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _sub(template: str, meta: dict[str, Any]) -> str:
    """Substitute *meta* values into *template*.

    Each occurrence of ``{{key}}`` is replaced with ``meta[key]`` if
    the key is present, otherwise it is replaced with ``[FILL IN]``.
    """
    import re

    def _replace(m: "re.Match[str]") -> str:
        key = m.group(1).strip()
        return str(meta.get(key, "[FILL IN]"))

    return re.sub(r"\{\{(\w+)\}\}", _replace, template)


_HEADER = """\
<!-- DO-178C Certification Artefact — generated by kerf-aero -->
<!-- Applicant must review, complete all [FILL IN] fields, and obtain DER review before submission. -->

# {{doc_type_title}}

**Project:** {{project_name}}
**DAL:** {{dal}}
**Aircraft / Platform:** {{aircraft_type}}
**Applicant:** {{applicant}}
**Document Version:** {{version}}
**Date:** {{date}}
**Author:** {{author}}
**DER / DQA:** {{dqa}}

---
"""


# ---------------------------------------------------------------------------
# Individual document templates
# ---------------------------------------------------------------------------

_PSAC = (
    _HEADER
    + """\
## 1  System Overview

### 1.1  System Description

[FILL IN — Describe the airborne system in which this software component
executes, its operational context, and mission objectives.]

### 1.2  Software Overview

[FILL IN — Describe the software component: programming language(s),
target processor, operating system / RTOS, approximate size (SLOC).]

### 1.3  Software Function

[FILL IN — List the functions this software performs within the system.]

---

## 2  Certification Basis

### 2.1  Applicable Regulations

[FILL IN — e.g., 14 CFR Part 23 / Part 25 / Part 27 / Part 29; EASA
CS-23 / CS-25; applicable amendment levels.]

### 2.2  Means of Compliance

[FILL IN — Reference AC 20-115D / AMC 20-115D and the applicable
DO-178C supplement(s) (DO-330, DO-331, DO-332, DO-333).]

### 2.3  Design Assurance Level

Software DAL: **{{dal}}** — [FILL IN — failure condition category and
effect per ARP 4761 / AC 25.1309.]

---

## 3  Software Life-Cycle

### 3.1  Software Life-Cycle Processes

[FILL IN — Identify the software life-cycle processes: planning,
development (requirements, design, code, integration), verification,
configuration management, quality assurance, and certification liaison.]

### 3.2  Software Life-Cycle Environment

| Item                | Description |
|---------------------|-------------|
| Development host OS | [FILL IN]   |
| Compiler / Toolchain | [FILL IN]  |
| Compiler version    | [FILL IN]   |
| Linker              | [FILL IN]   |
| Target processor    | [FILL IN]   |
| Target OS / RTOS    | [FILL IN]   |
| Requirements tool   | [FILL IN]   |
| Version control     | [FILL IN]   |
| CI system           | [FILL IN]   |

### 3.3  Previously Developed Software (PDS)

[FILL IN — Identify any reused software components, COTS, or OSS, and
describe the credit sought and the gap analysis performed.]

---

## 4  Certification Coordination

### 4.1  Certification Authority Coordination

[FILL IN — Describe scheduled meetings, review gates, and anticipated
stage-of-involvement (SOI) audits with the certification authority.]

### 4.2  Stage of Involvement Plan

| SOI | Phase                         | Planned Date |
|-----|-------------------------------|--------------|
| 1   | Planning review               | [FILL IN]    |
| 2   | Development review            | [FILL IN]    |
| 3   | Verification review           | [FILL IN]    |
| 4   | Final compliance determination | [FILL IN]   |

---

## 5  Software Life-Cycle Data

### 5.1  Required Artefacts for DAL {{dal}}

[FILL IN — List all software life-cycle data items per DO-178C Table A-1
applicable to DAL {{dal}}. Reference the kerf-aero `dal_classifier`
`required_artefacts_do178c("{{dal}}")` output for the full list.]

### 5.2  Data Control Categories

| Artefact | CC1 / CC2 | Location |
|----------|-----------|----------|
| PSAC     | CC2       | [FILL IN] |
| SDP      | CC2       | [FILL IN] |
| SVP      | CC2       | [FILL IN] |
| SCMP     | CC2       | [FILL IN] |
| SQAP     | CC2       | [FILL IN] |
| HLR      | CC2       | [FILL IN] |
| LLR      | CC2       | [FILL IN] |
| SDD      | CC1       | [FILL IN] |
| Source Code | CC1    | [FILL IN] |
| Test Cases | CC2     | [FILL IN] |
| Test Results | CC1   | [FILL IN] |
| SAS      | CC2       | [FILL IN] |

---

## 6  Schedule

[FILL IN — Provide a top-level milestone schedule cross-referenced to
the Stage of Involvement plan above.]

---

## 7  Additional Considerations

### 7.1  Tool Qualification

[FILL IN — Identify any development or verification tools that require
qualification per DO-330.  For each tool state the TQL level.]

### 7.2  Alternative Methods

[FILL IN — Identify any alternative methods proposed per DO-178C §12.]

### 7.3  Multiple-Version Dissimilar Software

[FILL IN — If applicable.]

---

## 8  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of PSAC*
"""
)

_SDP = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This Software Development Plan (SDP) defines the software development
processes and standards for **{{project_name}}** (DAL {{dal}}).

### 1.2  Scope

[FILL IN — Describe what software is covered by this SDP.]

### 1.3  Reference Documents

| Reference | Title |
|-----------|-------|
| RTCA DO-178C | Software Considerations in Airborne Systems and Equipment Certification |
| [FILL IN] | System Requirements Specification |
| [FILL IN] | PSAC |

---

## 2  Software Development Environment

### 2.1  Language and Coding Standard

- **Programming Language:** [FILL IN]
- **Language Standard:** [FILL IN — e.g., C99, C++14, Ada 2012]
- **Coding Standard:** [FILL IN — e.g., MISRA C:2012, CERT C]
- **Code Review Checklist:** [FILL IN]

### 2.2  Development Toolchain

[FILL IN — Describe compiler, build system, static analysers, and their
qualification status per DO-330 if applicable.]

### 2.3  Target Hardware

[FILL IN — Processor, clock speed, memory map, I/O interface summary.]

---

## 3  Software Requirements Process

### 3.1  High-Level Requirements

[FILL IN — Describe the process for deriving HLR from system requirements,
including review and approval workflow.]

### 3.2  Low-Level Requirements

[FILL IN — Describe the process for deriving LLR from HLR, including
traceability discipline and review workflow.]

### 3.3  Derived Requirements

[FILL IN — Describe how derived requirements are identified and fed back
to the system safety assessment process per DO-178C §5.1.]

---

## 4  Software Design Process

### 4.1  Architecture

[FILL IN — Describe partitioning strategy, inter-module interfaces,
scheduling, and any certified partitioning technology used.]

### 4.2  Design Standards

[FILL IN — Reference design standards: naming conventions, module size
limits, recursion prohibition, dynamic memory usage policy, etc.]

---

## 5  Coding Process

### 5.1  Coding Standards

[FILL IN — Reference adopted coding standard and any project-specific
deviations with rationale.]

### 5.2  Code Review

[FILL IN — Describe the code-review process: tool-assisted review, peer
review, independence requirements for DAL {{dal}}.]

---

## 6  Integration Process

### 6.1  Software Integration

[FILL IN — Describe how software modules are integrated, link-map
verification, and integration test sequence.]

### 6.2  Hardware / Software Integration

[FILL IN — Describe target-hardware integration, environment checks, and
who owns the integration test bench.]

---

## 7  Traceability

[FILL IN — Describe the requirements traceability process from system
requirements down to source code and tests, and the tooling used
(e.g., kerf-aero `.req.json` / `.test.json` scaffolding).]

---

## 8  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of SDP*
"""
)

_SVP = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This Software Verification Plan (SVP) describes the verification activities
for **{{project_name}}** (DAL {{dal}}).

### 1.2  Scope

[FILL IN — Identify the software components and artefacts covered.]

### 1.3  Reference Documents

| Reference | Title |
|-----------|-------|
| RTCA DO-178C | Software Considerations in Airborne Systems and Equipment Certification |
| SDP | Software Development Plan |
| HLR | High-Level Requirements |

---

## 2  Verification Environment

### 2.1  Test Host

[FILL IN — OS, hardware, installed verification toolchain.]

### 2.2  Verification Tools

| Tool | Version | TQL (DO-330) |
|------|---------|--------------|
| [FILL IN] | [FILL IN] | [FILL IN] |

### 2.3  Target / Simulation

[FILL IN — Describe whether testing is on target hardware, a simulation,
or both.  Justify adequacy per DO-178C §4.4.]

---

## 3  Verification of High-Level Requirements

### 3.1  Reviews

[FILL IN — Process for reviewing HLR for correctness, consistency,
verifiability, conformance to standards, and traceability to system
requirements.]

### 3.2  Tests

[FILL IN — Test strategy for normal range, robustness, boundary, and
boundary-plus-one inputs.]

---

## 4  Verification of Low-Level Requirements

### 4.1  Reviews

[FILL IN — Review process for LLR checking derived requirements are fed
back to safety assessment.]

### 4.2  Tests

[FILL IN — Test strategy ensuring every LLR has at least one test case.]

---

## 5  Verification of Source Code

### 5.1  Code Reviews

[FILL IN — Static analysis tools, peer review checklist, compliance
check against coding standard.]

### 5.2  Structural Coverage Analysis

DAL {{dal}} requires the following coverage:

| Coverage Type       | Required for DAL {{dal}} |
|---------------------|--------------------------|
| Statement coverage  | [FILL IN — Yes/No]       |
| Decision coverage   | [FILL IN — Yes/No]       |
| MC/DC               | [FILL IN — Yes/No]       |

[FILL IN — Describe the coverage measurement tool, acceptable coverage
level, and the process for analysing and resolving coverage gaps
(dead code justification, additional test cases).]

---

## 6  Verification Independence

[FILL IN — Describe the independence required for DAL {{dal}} per
DO-178C Table A-7 and how it is achieved (separate team / tool-based).]

---

## 7  Regression Strategy

[FILL IN — Describe the regression test trigger (every commit, every
build, before release), the regression test suite composition, and
acceptable regression policy.]

---

## 8  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of SVP*
"""
)

_SCMP = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This Software Configuration Management Plan (SCMP) defines the CM
processes for **{{project_name}}** (DAL {{dal}}).

### 1.2  Scope

[FILL IN — List the CI items under CM control.]

---

## 2  Configuration Identification

### 2.1  Configuration Items

| CI Name | Type | Current Baseline |
|---------|------|-----------------|
| [FILL IN] | Source Code | [FILL IN] |
| [FILL IN] | Test Cases | [FILL IN] |
| [FILL IN] | Build Scripts | [FILL IN] |
| [FILL IN] | Documents | [FILL IN] |

### 2.2  Naming Convention

[FILL IN — Document the part-number or naming scheme for all CIs.]

---

## 3  Baselines

### 3.1  Development Baseline

[FILL IN — Define when the development baseline is established and how
deviations are controlled.]

### 3.2  Product Baseline

[FILL IN — Define the product baseline established at release and the
approval process.]

---

## 4  Change Control

### 4.1  Problem Reporting

[FILL IN — Describe the problem report lifecycle: submission, triage,
impact assessment, approval, implementation, and closure.]

### 4.2  Change Control Board

[FILL IN — Membership, quorum, decision authority, and meeting cadence.]

---

## 5  Configuration Status Accounting

[FILL IN — Describe how CM status is tracked and reported, including
the Software Configuration Index (SCI) update process.]

---

## 6  Archive and Retrieval

[FILL IN — Describe the archive medium, retention period (typically
life-of-type + 10 years), and retrieval procedure.]

---

## 7  CM Audits

[FILL IN — Functional Configuration Audit (FCA) and Physical
Configuration Audit (PCA) scope, schedule, and acceptance criteria.]

---

## 8  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of SCMP*
"""
)

_SQAP = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This Software Quality Assurance Plan (SQAP) defines the QA activities
for **{{project_name}}** (DAL {{dal}}).

### 1.2  Scope

[FILL IN — Identify software products and processes covered by this plan.]

---

## 2  Software Quality Assurance Organisation

### 2.1  SQA Authority

[FILL IN — Describe the SQA function's independence from the development
team and its authority to escalate non-compliances.]

### 2.2  Responsibilities

| Role | Responsibility |
|------|----------------|
| SQA Lead | [FILL IN] |
| Development Lead | [FILL IN] |
| Project Manager | [FILL IN] |

---

## 3  QA Activities

### 3.1  Plan Compliance Reviews

[FILL IN — Schedule and scope of reviews to verify conformance with PSAC,
SDP, SVP, and SCMP.]

### 3.2  Software Life-Cycle Process Audits

[FILL IN — Describe the audit approach: planned vs. spot audits, audit
checklists, and the non-conformance escalation path.]

### 3.3  Transition Criteria Reviews

[FILL IN — For each life-cycle phase transition (planning→development,
development→verification, verification→release) describe the entrance
and exit criteria review.]

---

## 4  Non-Conformance Management

### 4.1  Identification and Recording

[FILL IN — Describe how non-conformances are captured (problem report
system, deviation record, waiver).]

### 4.2  Disposition and Closure

[FILL IN — Describe the approval chain for dispositions and the
verification of corrective actions.]

---

## 5  QA Records

[FILL IN — List the QA records retained, their location, and retention
period.]

---

## 6  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of SQAP*
"""
)

_HLR = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This document captures the High-Level Requirements (HLR) for
**{{project_name}}** (DAL {{dal}}).  HLRs are derived from the System
Requirements Specification and serve as the top-level software
specification.

### 1.2  Scope

[FILL IN — Describe the functional boundaries of the software component.]

---

## 2  System Context

### 2.1  System Requirements Traceability

| HLR ID | System Req ID | Derived? | Description |
|--------|---------------|----------|-------------|
| HLR-001 | SYS-[FILL IN] | No | [FILL IN] |
| HLR-002 | SYS-[FILL IN] | No | [FILL IN] |
| HLR-DRV-001 | — | Yes | [FILL IN — describe derived requirement and safety assessment feedback] |

### 2.2  External Interfaces

| Interface | Direction | Protocol | Description |
|-----------|-----------|----------|-------------|
| [FILL IN] | IN / OUT  | [FILL IN] | [FILL IN]  |

---

## 3  Functional Requirements

### 3.1  Normal Operation

[FILL IN — HLR narrative and table for normal operating conditions.]

| HLR ID | Shall Statement | Verification Method |
|--------|-----------------|---------------------|
| HLR-003 | The software shall [FILL IN] | Test |
| HLR-004 | The software shall [FILL IN] | Analysis |

### 3.2  Failure / Abnormal Operation

[FILL IN — Describe software behaviour under input faults, hardware
faults, and power interruption.]

---

## 4  Performance Requirements

| HLR ID | Parameter | Threshold | Verification |
|--------|-----------|-----------|--------------|
| HLR-P01 | [FILL IN] | [FILL IN] | Test |

---

## 5  Safety Requirements

[FILL IN — List all safety-critical HLRs and their relationship to the
FMEA / FTA results from the system safety assessment.]

---

## 6  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of HLR*
"""
)

_LLR = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This document captures the Low-Level Requirements (LLR) for
**{{project_name}}** (DAL {{dal}}).  LLRs are derived from the
High-Level Requirements and the Software Design Description; they
must be of sufficient detail to allow direct implementation and test
without further design decisions.

### 1.2  Scope

[FILL IN — Module or subsystem covered by these LLRs.]

---

## 2  HLR Traceability

| LLR ID | HLR ID | Derived? | Description |
|--------|--------|----------|-------------|
| LLR-001 | HLR-001 | No | [FILL IN] |
| LLR-002 | HLR-002 | No | [FILL IN] |
| LLR-DRV-001 | — | Yes | [FILL IN] |

---

## 3  Module-Level Requirements

### 3.1  Inputs

| Signal / Variable | Type | Range | Units | Source |
|-------------------|------|-------|-------|--------|
| [FILL IN] | [FILL IN] | [FILL IN] | [FILL IN] | [FILL IN] |

### 3.2  Outputs

| Signal / Variable | Type | Range | Units | Destination |
|-------------------|------|-------|-------|-------------|
| [FILL IN] | [FILL IN] | [FILL IN] | [FILL IN] | [FILL IN] |

### 3.3  Processing Requirements

[FILL IN — Algorithmic / state-machine LLRs with sufficient precision
that an independent programmer could implement them correctly.  Include
numeric tolerances, data type sizes, overflow-handling, and IPC
protocols.]

| LLR ID | Shall Statement |
|--------|-----------------|
| LLR-003 | The {{project_name}} module shall [FILL IN] |

---

## 4  Timing Requirements

| LLR ID | Requirement | Budget |
|--------|-------------|--------|
| LLR-T01 | Worst-case execution time shall not exceed | [FILL IN] ms |

---

## 5  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of LLR*
"""
)

_SDD = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This Software Design Description (SDD) for **{{project_name}}**
(DAL {{dal}}) describes the software architecture, module decomposition,
and interfaces in sufficient detail to guide correct implementation and
to support LLR-to-code traceability.

### 1.2  Scope

[FILL IN — List the modules and files described herein.]

---

## 2  Software Architecture

### 2.1  Architectural Overview

[FILL IN — Describe the top-level partitioning, execution model (bare-
metal / RTOS / OS), task/interrupt structure, and key data flows.
Include or reference an architecture diagram.]

### 2.2  Software Partitions

| Partition | Safety Level | Description |
|-----------|-------------|-------------|
| [FILL IN] | DAL {{dal}} | [FILL IN]  |
| [FILL IN] | DAL [FILL IN] | [FILL IN] |

### 2.3  Execution Model

[FILL IN — Describe the scheduling scheme: cyclic executive, RTOS
tasks, priorities, periods, and interrupt handling.]

---

## 3  Module Descriptions

### 3.1  Module: [FILL IN]

**File(s):** `[FILL IN]`
**LLR(s) implemented:** LLR-[FILL IN]

#### 3.1.1  Interface

| Parameter | Direction | Type | Description |
|-----------|-----------|------|-------------|
| [FILL IN] | in/out    | [FILL IN] | [FILL IN] |

#### 3.1.2  Algorithm Description

[FILL IN — Describe the algorithm implemented in this module with
pseudo-code or mathematical notation where helpful.]

#### 3.1.3  Error Handling

[FILL IN — Describe detection and handling of erroneous inputs,
computation overflows, and hardware faults within this module.]

---

## 4  Data Design

### 4.1  Global Data Structures

| Name | Type | Ownership | Description |
|------|------|-----------|-------------|
| [FILL IN] | [FILL IN] | [FILL IN module] | [FILL IN] |

### 4.2  IPC / Message Queues

[FILL IN — Describe any message-passing or shared-memory IPC, its
protection mechanisms, and access protocol.]

---

## 5  LLR-to-Code Traceability Index

| LLR ID | Source File | Function / Line |
|--------|-------------|-----------------|
| LLR-001 | [FILL IN.c] | [FILL IN()] |

---

## 6  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of SDD*
"""
)

_SVCP = (
    _HEADER
    + """\
## 1  Introduction

### 1.1  Purpose

This Software Verification Cases and Procedures (SVCP) document defines
the test cases, procedures, and expected results used to verify
**{{project_name}}** (DAL {{dal}}) against its requirements.

### 1.2  Scope

[FILL IN — Identify the requirements documents and software artefacts
under test.]

---

## 2  Test Environment

### 2.1  Test Configuration

[FILL IN — Describe the test host, target hardware / simulator, test
harness software, and any required calibration records.]

### 2.2  Test Data

[FILL IN — Describe the origin and validation of test input data (e.g.,
measured flight data, synthesised edge-cases, DO-178C §6.4.2 range
tests).]

---

## 3  High-Level Requirement Tests

### 3.1  Normal Range Tests

| TC ID | HLR ID | Input | Expected Output | Pass Criteria |
|-------|--------|-------|-----------------|---------------|
| TC-HLR-001 | HLR-001 | [FILL IN] | [FILL IN] | [FILL IN] |

### 3.2  Robustness Tests

| TC ID | HLR ID | Fault Injected | Expected Behaviour |
|-------|--------|----------------|-------------------|
| TC-ROB-001 | HLR-[FILL IN] | [FILL IN] | [FILL IN] |

---

## 4  Low-Level Requirement Tests

| TC ID | LLR ID | Test Procedure | Expected Result |
|-------|--------|----------------|-----------------|
| TC-LLR-001 | LLR-001 | [FILL IN] | [FILL IN] |

---

## 5  Structural Coverage

### 5.1  Coverage Objectives for DAL {{dal}}

[FILL IN — State the required coverage types and targets for DAL {{dal}}
(see SVP §5.2).]

### 5.2  Untested Code Justification

[FILL IN — For any code not exercised by test cases, provide a
justification (e.g., dead code by design, defensive programming). Each
justification requires DER approval.]

---

## 6  Regression Suite

[FILL IN — Describe the subset of test cases that constitute the
regression suite, the trigger condition for running regression, and
the acceptable results.]

---

## 7  Document History

| Version | Date | Author | Description |
|---------|------|--------|-------------|
| 1.0     | {{date}} | {{author}} | Initial release |

---

*End of SVCP*
"""
)


# ---------------------------------------------------------------------------
# Mapping and public API
# ---------------------------------------------------------------------------

_TEMPLATES: dict[str, str] = {
    "PSAC": _PSAC,
    "SDP": _SDP,
    "SVP": _SVP,
    "SCMP": _SCMP,
    "SQAP": _SQAP,
    "HLR": _HLR,
    "LLR": _LLR,
    "SDD": _SDD,
    "SVCP": _SVCP,
}

_DOC_TITLES: dict[str, str] = {
    "PSAC": "Plan for Software Aspects of Certification (PSAC)",
    "SDP": "Software Development Plan (SDP)",
    "SVP": "Software Verification Plan (SVP)",
    "SCMP": "Software Configuration Management Plan (SCMP)",
    "SQAP": "Software Quality Assurance Plan (SQAP)",
    "HLR": "High-Level Requirements (HLR)",
    "LLR": "Low-Level Requirements (LLR)",
    "SDD": "Software Design Description (SDD)",
    "SVCP": "Software Verification Cases and Procedures (SVCP)",
}


def generate_template(doc_type: str, project_meta: dict[str, Any] | None = None) -> str:
    """Return a Markdown skeleton for *doc_type* with placeholders filled.

    Parameters
    ----------
    doc_type:
        One of ``SUPPORTED_DOC_TYPES`` (e.g. ``"PSAC"``, ``"SDP"``).
        Case-insensitive.
    project_meta:
        Optional dict of project-level values.  Recognised keys:
        ``project_name``, ``dal``, ``aircraft_type``, ``applicant``,
        ``version``, ``date``, ``author``, ``dqa``.  Unknown keys are
        ignored.  Missing keys produce ``[FILL IN]`` in the output.

    Returns
    -------
    str
        Markdown document with ``[FILL IN]`` placeholders for any
        project-meta fields not supplied.

    Raises
    ------
    ValueError
        If *doc_type* is not in ``SUPPORTED_DOC_TYPES``.
    """
    key = doc_type.strip().upper()
    if key not in _TEMPLATES:
        valid = ", ".join(SUPPORTED_DOC_TYPES)
        raise ValueError(
            f"Unknown DO-178C doc_type {doc_type!r}. Valid values: {valid}"
        )

    meta: dict[str, Any] = dict(project_meta or {})
    meta["doc_type_title"] = _DOC_TITLES[key]
    # Ensure DAL placeholder is consistent
    if "dal" not in meta:
        meta["dal"] = "[FILL IN]"

    return _sub(_TEMPLATES[key], meta)
